import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.79.0";

const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
const env = (name: string) => Deno.env.get(name) || "";
const supabaseUrl = env("SUPABASE_URL") || env("EXTERNAL_SUPABASE_URL");
const serviceKey = env("SUPABASE_SERVICE_ROLE_KEY") || env("EXTERNAL_SUPABASE_SERVICE_ROLE_KEY");
const anonKey = env("SUPABASE_ANON_KEY") || env("EXTERNAL_SUPABASE_ANON_KEY");
const bucket = "adminos-company-documents";
const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] || c));
const render = (template: string, data: Record<string, unknown>) => template.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_m, key) => escapeHtml(data[key] ?? ""));
const checksum = async (text: string) => { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text)); return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join(""); };
const docNumber = () => { const d = new Date(); const date = `${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}`; return `RK-${date}-${crypto.randomUUID().slice(0,8).toUpperCase()}`; };
const brandedHtml = (title: string, inner: string, number: string) => `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><style>body{font-family:Arial,Helvetica,sans-serif;color:#172033;background:#fff;margin:0}main{max-width:820px;margin:0 auto;padding:52px 56px}.brand{font-size:24px;font-weight:800;letter-spacing:.02em}.rule{height:4px;background:linear-gradient(90deg,#6c4cff,#18b7a0,#ffb020);margin:14px 0 28px}.meta{font-size:12px;color:#697386;margin-bottom:30px}.content{font-size:15px;line-height:1.65}.content h1{font-size:26px;line-height:1.2}.footer{margin-top:48px;padding-top:18px;border-top:1px solid #e6e9ef;font-size:11px;color:#7a8292}</style></head><body><main><div class="brand">RESKONNECT</div><div class="rule"></div><div class="meta">Document ${escapeHtml(number)} · Generated by ResKonnect AdminOS</div><div class="content">${inner}</div><div class="footer">Connecting Residents. Advancing Futures. · Internal record retained in ResKonnect AdminOS.</div></main></body></html>`;

async function staff(req: Request) {
  if (!supabaseUrl || !serviceKey || !anonKey) return { ok: false, service: null as any, user: null as any, role: null as any };
  const authHeader = req.headers.get("Authorization") || "";
  const auth = createClient(supabaseUrl, anonKey, { global: { headers: { Authorization: authHeader } } });
  const service = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } });
  const { data } = await auth.auth.getUser(); const user = data?.user;
  if (!user) return { ok: false, service, user: null, role: null };
  const roleRes = await service.rpc("get_user_staff_role", { _user_id: user.id });
  return { ok: Boolean(roleRes.data), service, user, role: roleRes.data || null };
}
async function upload(service: any, path: string, content: string) { const file = new Blob([content], { type: "text/html;charset=utf-8" }); const { error } = await service.storage.from(bucket).upload(path, file, { contentType: "text/html;charset=utf-8", upsert: true }); if (error) throw error; }
async function makeApproval(service: any, doc: any, preview: string) {
  const approval = await service.from("adminos_approval_requests").insert({ request_type: "company_document_finalize", title: `Approve document: ${doc.title}`, summary: `${doc.document_number} requires human approval before finalisation.`, entity_type: "company_document", entity_id: doc.id, requested_action: { document_id: doc.id, document_number: doc.document_number, title: doc.title, risk_level: doc.risk_level, preview: preview.slice(0, 1200) }, risk_level: doc.risk_level === "red" ? "red" : "amber", requested_by_type: "agent" }).select("id").single();
  if (approval.error) throw approval.error;
  await service.from("adminos_company_documents").update({ status: "awaiting_approval", approval_id: approval.data.id }).eq("id", doc.id);
  return approval.data.id;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: cors });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);
  const authz = await staff(req); if (!authz.ok) return json({ error: "Staff access required" }, 403);
  const service = authz.service; const body = await req.json().catch(() => ({})); const action = String(body.action || "health");
  if (action === "health") { const [templateCount, docCount] = await Promise.all([service.from("adminos_document_templates").select("id", { count: "exact", head: true }).eq("active", true), service.from("adminos_company_documents").select("id", { count: "exact", head: true })]); return json({ ok: true, active_templates: templateCount.count || 0, documents: docCount.count || 0, bucket, release: 3, phase: 8 }); }
  if (action === "generate") {
    const templateKey = String(body.template_key || ""); if (!templateKey) return json({ error: "template_key is required" }, 400);
    const tmpl = await service.from("adminos_document_templates").select("*").eq("template_key", templateKey).eq("active", true).maybeSingle(); if (!tmpl.data) return json({ error: "Template not found or inactive" }, 404);
    const mergeData = typeof body.merge_data === "object" && body.merge_data ? body.merge_data : {}; const required = Array.isArray(tmpl.data.variables) ? tmpl.data.variables : [];
    const missing = required.filter((key: string) => mergeData[key] === undefined || mergeData[key] === null || String(mergeData[key]).trim() === ""); if (missing.length) return json({ error: "Required variables are missing", missing }, 400);
    const number = docNumber(); const title = String(body.title || tmpl.data.name); const inner = render(tmpl.data.content_template, mergeData); const html = brandedHtml(title, inner, number); const risk = tmpl.data.risk_level || "green";
    const initialStatus = (tmpl.data.requires_approval || risk !== "green") ? "awaiting_approval" : (body.finalize === true ? "finalized" : "draft"); const path = `${new Date().getUTCFullYear()}/${number}/v1.html`;
    const created = await service.from("adminos_company_documents").insert({ document_number: number, template_id: tmpl.data.id, document_type: String(body.document_type || tmpl.data.template_key), category: tmpl.data.category || "general", title, status: initialStatus, risk_level: risk, contact_id: body.contact_id || null, organization_id: body.organization_id || null, application_id: body.application_id || null, current_version: 1, storage_bucket: bucket, storage_path: path, metadata: { release: 3, phase: 8, template_key: templateKey, generated_by: "adminos-paperwork" }, created_by: authz.user.id, finalized_at: initialStatus === "finalized" ? new Date().toISOString() : null }).select("*").single();
    if (created.error) return json({ error: created.error.message }, 409);
    try {
      const hash = await checksum(html); await upload(service, path, html);
      await service.from("adminos_company_document_versions").insert({ document_id: created.data.id, version: 1, content_text: html, merge_data: mergeData, change_note: "Initial generated version", storage_path: path, checksum: hash, created_by: authz.user.id });
      await service.from("adminos_company_document_events").insert({ document_id: created.data.id, event_type: "generated", actor_type: "staff", actor_id: authz.user.id, detail: { template_key: templateKey, risk_level: risk, status: initialStatus } });
      let approvalId: string | null = null; if (initialStatus === "awaiting_approval") approvalId = await makeApproval(service, created.data, inner);
      const signed = await service.storage.from(bucket).createSignedUrl(path, 600); return json({ ok: true, document: { ...created.data, status: initialStatus, approval_id: approvalId }, preview_url: signed.data?.signedUrl || null, release: 3, phase: 8 });
    } catch (e) { await service.from("adminos_company_documents").delete().eq("id", created.data.id); return json({ error: e instanceof Error ? e.message : String(e) }, 500); }
  }
  if (action === "revise") {
    const id = String(body.document_id || ""); if (!id) return json({ error: "document_id is required" }, 400);
    const doc = await service.from("adminos_company_documents").select("*,adminos_document_templates(*)").eq("id", id).maybeSingle(); if (!doc.data) return json({ error: "Document not found" }, 404); if (doc.data.status === "archived") return json({ error: "Archived documents cannot be revised" }, 409);
    const tmpl = doc.data.adminos_document_templates; if (!tmpl) return json({ error: "Template unavailable" }, 409); const mergeData = typeof body.merge_data === "object" && body.merge_data ? body.merge_data : {}; const required = Array.isArray(tmpl.variables) ? tmpl.variables : [];
    const missing = required.filter((key: string) => mergeData[key] === undefined || mergeData[key] === null || String(mergeData[key]).trim() === ""); if (missing.length) return json({ error: "Required variables are missing", missing }, 400);
    const version = Number(doc.data.current_version || 1) + 1; const inner = render(tmpl.content_template, mergeData); const html = brandedHtml(doc.data.title, inner, doc.data.document_number); const path = `${new Date().getUTCFullYear()}/${doc.data.document_number}/v${version}.html`; const hash = await checksum(html);
    await upload(service, path, html); await service.from("adminos_company_document_versions").insert({ document_id: id, version, content_text: html, merge_data: mergeData, change_note: String(body.change_note || "Revised version"), storage_path: path, checksum: hash, created_by: authz.user.id });
    const needsApproval = tmpl.requires_approval || doc.data.risk_level !== "green"; await service.from("adminos_company_documents").update({ current_version: version, storage_path: path, status: needsApproval ? "awaiting_approval" : "draft", approval_id: null, approved_by: null, finalized_at: null }).eq("id", id);
    let approvalId: string | null = null; if (needsApproval) approvalId = await makeApproval(service, { ...doc.data, current_version: version }, inner);
    await service.from("adminos_company_document_events").insert({ document_id: id, event_type: "revised", actor_type: "staff", actor_id: authz.user.id, detail: { version, approval_id: approvalId } }); return json({ ok: true, document_id: id, version, approval_id: approvalId });
  }
  if (action === "finalize") {
    const id = String(body.document_id || ""); const doc = await service.from("adminos_company_documents").select("*").eq("id", id).maybeSingle(); if (!doc.data) return json({ error: "Document not found" }, 404);
    if (doc.data.status === "awaiting_approval") return json({ error: "Human approval is still required" }, 409); if (doc.data.risk_level !== "green" && doc.data.status !== "approved") return json({ error: "Sensitive document must be approved before finalisation" }, 409);
    await service.from("adminos_company_documents").update({ status: "finalized", finalized_at: new Date().toISOString(), approved_by: doc.data.approved_by || authz.user.id }).eq("id", id); await service.from("adminos_company_document_events").insert({ document_id: id, event_type: "finalized", actor_type: "staff", actor_id: authz.user.id, detail: { version: doc.data.current_version } });
    const signed = doc.data.storage_path ? await service.storage.from(bucket).createSignedUrl(doc.data.storage_path, 600) : { data: null }; return json({ ok: true, document_id: id, status: "finalized", download_url: signed.data?.signedUrl || null });
  }
  if (action === "signed_url") { const id = String(body.document_id || ""); const doc = await service.from("adminos_company_documents").select("storage_path").eq("id", id).maybeSingle(); if (!doc.data?.storage_path) return json({ error: "Document file not found" }, 404); const signed = await service.storage.from(bucket).createSignedUrl(doc.data.storage_path, Math.max(60, Math.min(3600, Number(body.expires_in || 600)))); if (signed.error) return json({ error: signed.error.message }, 500); return json({ ok: true, url: signed.data.signedUrl }); }
  if (action === "archive") { const id = String(body.document_id || ""); const doc = await service.from("adminos_company_documents").select("id").eq("id", id).maybeSingle(); if (!doc.data) return json({ error: "Document not found" }, 404); await service.from("adminos_company_documents").update({ status: "archived", archived_at: new Date().toISOString() }).eq("id", id); await service.from("adminos_company_document_events").insert({ document_id: id, event_type: "archived", actor_type: "staff", actor_id: authz.user.id, detail: {} }); return json({ ok: true, document_id: id, status: "archived" }); }
  return json({ error: "Unsupported action" }, 400);
});
