import type { OnboardingRequest } from "./onboardingTypes";

// Seed data used by the admin Onboarding Hub while the backend table is pending.
// TODO: connect to Supabase onboarding_requests after backend migration is deployed.
export const MOCK_ONBOARDING_REQUESTS: OnboardingRequest[] = [
  {
    id: "seed-1",
    persona: "student",
    need: "accommodation",
    full_name: "Thandi Mokoena",
    phone: "0712345678",
    whatsapp_number: "0712345678",
    email: "reskonnect@gmail.com",
    consent_to_be_contacted: true,
    popia_consent: true,
    details: { preferred_campus: "Soshanguve South", institution: "TUT" },
    status: "new",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "seed-2",
    persona: "parent_guardian",
    need: "application_support",
    full_name: "Sipho Nkosi",
    phone: "0823456789",
    whatsapp_number: "0823456789",
    email: "reskonnect@gmail.com",
    consent_to_be_contacted: true,
    popia_consent: true,
    details: {
      student_full_name: "Lerato Nkosi",
      relationship_to_student: "Father",
      preferred_institution: "TUT",
    },
    status: "in_review",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  },
  {
    id: "seed-3",
    persona: "landlord",
    need: "property_listing",
    full_name: "Naledi Properties (Pty) Ltd",
    phone: "0119876543",
    email: "hello@naledi.co.za",
    consent_to_be_contacted: true,
    popia_consent: true,
    details: { property_name: "Naledi Court", number_of_rooms_or_units: 42 },
    status: "contacted",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "seed-4",
    persona: "wil_applicant",
    need: "wil_support",
    full_name: "Karabo Dlamini",
    phone: "0734567890",
    email: "reskonnect@gmail.com",
    consent_to_be_contacted: true,
    popia_consent: true,
    details: { course: "IT Software Development", year_or_level: "N6" },
    status: "new",
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "seed-5",
    persona: "unsure",
    need: "general_guidance",
    full_name: "Anonymous Visitor",
    consent_to_be_contacted: false,
    popia_consent: true,
    details: { message: "Not sure where to start." },
    status: "new",
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
];