import { useCallback, useEffect, useMemo, useState } from "react";
import { ExternalLink, RefreshCw, Sheet } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { CAMPUS_OPTIONS_BY_PROVINCE, extractServedCampuses, isSoshaResidence, setSoshaTag, toggleCampusInResidence, validateResidenceCampusPolicy } from "@/lib/residenceCampusPolicy";

const SHEET="https://docs.google.com/spreadsheets/d/1x18MYICyLHL_1YvgpquZ4rbrdGovUmuWxjy45cHY1Ek/edit";
const CSV="https://www.reskonnect.org/api/meta-residence-feed?format=csv";
const PROVINCES=["Gauteng","Western Cape","KwaZulu-Natal","Eastern Cape","Free State","Limpopo","Mpumalanga","North West","Northern Cape"];

export default function AdminMetaResidenceManager(){
  const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[editing,setEditing]=useState<any|null>(null),[saving,setSaving]=useState(false),[live,setLive]=useState<number|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const r=await(supabase as any).from("residences").select("id,name,campus,province,address,city,institution_tags,is_visible").order("name").limit(5000);if(r.error)throw r.error;setRows(r.data||[]);const f=await fetch("/api/meta-residence-feed?format=json");const d=await f.json();if(f.ok)setLive(Number(d.row_count||0));}catch(e:any){toast.error(e?.message||"Could not load Meta feed");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const audited=useMemo(()=>rows.map(row=>({row,policy:validateResidenceCampusPolicy(row)})),[rows]);
  const bad=audited.filter(x=>!x.policy.valid),sosha=audited.filter(x=>x.policy.soshaException).length;
  const visible=audited.filter(({row,policy})=>{const n=q.toLowerCase();return !n||[row.name,row.campus,row.province,...policy.violations].filter(Boolean).join(" ").toLowerCase().includes(n);});
  const save=async()=>{if(!editing)return;const p=validateResidenceCampusPolicy(editing);if(!p.valid)return toast.error(p.violations[0]);setSaving(true);const r=await(supabase as any).from("residences").update({campus:editing.campus||null,province:editing.province||null,institution_tags:editing.institution_tags||[]}).eq("id",editing.id);setSaving(false);if(r.error)return toast.error(r.error.message);toast.success("Meta eligibility updated");setEditing(null);void load();};
  return <div className="space-y-5">
    <div className="rounded-[28px] border bg-background p-5 shadow-sm">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><Badge className="rounded-full"><Sheet className="mr-1 h-3.5 w-3.5"/>Meta Residence Feed</Badge><h3 className="mt-3 text-2xl font-black">Supabase controls the Sheet.</h3><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Multiple campuses are allowed only inside one province. Pretoria West may serve Soshanguve only for Ekhaya Junction or an explicitly SOSHA-tagged residence.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()}><RefreshCw className={loading?"mr-2 h-4 w-4 animate-spin":"mr-2 h-4 w-4"}/>Refresh</Button><Button variant="outline" asChild><a href={SHEET} target="_blank" rel="noreferrer"><Sheet className="mr-2 h-4 w-4"/>Sheet</a></Button><Button asChild><a href={CSV} target="_blank" rel="noreferrer"><ExternalLink className="mr-2 h-4 w-4"/>CSV</a></Button></div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Live feed",live??"—"],["Policy clean",audited.length-bad.length],["Needs correction",bad.length],["SOSHA",sosha]].map(([label,value])=><div key={String(label)} className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>
    </div>
    <div className="rounded-[28px] border bg-background shadow-sm"><div className="border-b p-4"><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search residence, campus or province"/></div><div className="divide-y">{visible.slice(0,500).map(({row,policy})=><div key={row.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b>{row.name}</b><Badge variant={policy.valid?"outline":"destructive"}>{policy.valid?"Clean":"Fix"}</Badge>{policy.soshaException&&<Badge variant="secondary">SOSHA</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{row.province||"Province missing"} · {row.campus||"No campuses"}</p>{policy.violations.map((v:string)=><p key={v} className="mt-1 text-xs text-destructive">{v}</p>)}</div><Button size="sm" variant="outline" onClick={()=>setEditing({...row,institution_tags:row.institution_tags||[]})}>Edit eligibility</Button></div>)}</div></div>
    <Dialog open={!!editing} onOpenChange={open=>!open&&setEditing(null)}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Campus eligibility</DialogTitle></DialogHeader>{editing&&<div className="space-y-4"><div><b>{editing.name}</b><p className="text-xs text-muted-foreground">{editing.address}</p></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Province</Label><Select value={editing.province||"Gauteng"} onValueChange={province=>setEditing({...editing,province})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{PROVINCES.map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select></div><label className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">SOSHA exception</span><Switch checked={isSoshaResidence(editing)} onCheckedChange={v=>setEditing({...editing,institution_tags:setSoshaTag(editing.institution_tags,v)})}/></label></div><div><Label>Served campuses</Label><Input value={editing.campus||""} onChange={e=>setEditing({...editing,campus:e.target.value})}/><div className="mt-2 grid gap-2 sm:grid-cols-2">{(CAMPUS_OPTIONS_BY_PROVINCE[editing.province||"Gauteng"]||[]).map(c=><label key={c} className="flex items-center gap-2 rounded-lg border p-2 text-xs"><Checkbox checked={extractServedCampuses(editing.campus).includes(c)} onCheckedChange={v=>setEditing({...editing,campus:toggleCampusInResidence(editing.campus,c,v===true)})}/>{c}</label>)}</div></div>{!validateResidenceCampusPolicy(editing).valid&&<div className="rounded-xl border border-destructive/25 bg-destructive/5 p-3">{validateResidenceCampusPolicy(editing).violations.map((v:string)=><p key={v} className="text-xs text-destructive">{v}</p>)}</div>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={saving||!validateResidenceCampusPolicy(editing).valid} onClick={()=>void save()}>{saving?"Saving…":"Save"}</Button></div></div>}</DialogContent></Dialog>
  </div>;
}
