import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { ArrowLeft, Bot, Check, CheckCheck, CircleAlert, Download, FileText, Image as ImageIcon, Inbox, MessageCircle, Paperclip, RefreshCw, Search, Send, ShieldCheck, Sparkles, UserRound, UsersRound, X } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

type Mode = "ai_auto" | "assist" | "human" | "escalated" | "closed";
type Contact = { id:string; profile_user_id?:string|null; full_name?:string|null; email?:string|null; phone?:string|null; student_number?:string|null; campus?:string|null; contact_type?:string|null; metadata?:any; profile_picture_url?:string|null };
type Message = { id:string; thread_id:string; direction:"inbound"|"outbound"; body_text?:string|null; media?:any[]|null; status?:string|null; created_at:string; sent_at?:string|null; received_at?:string|null; delivered_at?:string|null; metadata?:any };
type Staff = { id:string; full_name?:string|null; email?:string|null };
type Thread = { id:string; contact_id?:string|null; channel_address:string; status:string; mode?:Mode|null; priority?:string|null; assigned_to?:string|null; unread_count?:number; last_message_at?:string|null; customer_window_expires_at?:string|null; last_summary?:string|null; tags?:any[]|null; contact?:Contact|null; lastMessage?:Message|null; assignee?:Staff|null };
type VaultFile = { id:string; message_id:string; thread_id:string; storage_bucket:string; storage_path:string; original_name?:string|null; content_type?:string|null; size_bytes?:number|null; created_at:string };

const filters = ["all","unread","ai_auto","assist","human","escalated"] as const;
type Filter = typeof filters[number];
const modeLabel=(mode:Mode|string)=>mode==="ai_auto"?"Dimpho Auto":mode==="assist"?"Assist":mode==="human"?"Human":mode==="escalated"?"Escalated":"Closed";
const phone=(value?:string|null)=>String(value||"").replace(/^whatsapp:/i,"");
const when=(value?:string|null)=>{if(!value)return"—";const ms=Date.now()-new Date(value).getTime();if(ms<60000)return"now";if(ms<3600000)return`${Math.floor(ms/60000)}m`;if(ms<86400000)return`${Math.floor(ms/3600000)}h`;return new Date(value).toLocaleDateString("en-ZA",{day:"2-digit",month:"short"});};
const initials=(value:string)=>String(value||"RK").trim().split(/\s+/).slice(0,2).map((p)=>p[0]).join("").toUpperCase()||"RK";

export default function AdminOSWhatsAppDeskNext(){
  const [searchParams]=useSearchParams();
  const [loading,setLoading]=useState(true);
  const [working,setWorking]=useState<string|null>(null);
  const [threads,setThreads]=useState<Thread[]>([]);
  const [messages,setMessages]=useState<Message[]>([]);
  const [staff,setStaff]=useState<Staff[]>([]);
  const [vault,setVault]=useState<VaultFile[]>([]);
  const [notes,setNotes]=useState<any[]>([]);
  const [templates,setTemplates]=useState<any[]>([]);
  const [selectedId,setSelectedId]=useState<string|null>(()=>searchParams.get("thread"));
  const [search,setSearch]=useState("");
  const [filter,setFilter]=useState<Filter>("all");
  const [composer,setComposer]=useState("");
  const [note,setNote]=useState("");
  const [attachment,setAttachment]=useState<File|null>(null);
  const [templateKey,setTemplateKey]=useState("");
  const [templateVars,setTemplateVars]=useState<Record<string,string>>({});
  const [mobileChat,setMobileChat]=useState(false);
  const [live,setLive]=useState(false);
  const fileRef=useRef<HTMLInputElement|null>(null);

  const invoke=useCallback(async(body:any)=>{const {data,error}=await (supabase.functions as any).invoke("adminos-whatsapp-desk",{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data;},[]);
  const selected=useMemo(()=>threads.find((t)=>t.id===selectedId)||null,[threads,selectedId]);
  const selectedTemplate=useMemo(()=>templates.find((t)=>t.template_key===templateKey)||null,[templates,templateKey]);
  const windowOpen=selected?.customer_window_expires_at?new Date(selected.customer_window_expires_at).getTime()>Date.now():false;

  const loadDesk=useCallback(async()=>{
    setLoading(true);
    try{
      const [tr,mr,sr,tar]=await Promise.all([
        (supabase as any).from("adminos_whatsapp_threads").select("*").order("last_message_at",{ascending:false}).limit(250),
        (supabase as any).from("adminos_whatsapp_messages").select("*").order("created_at",{ascending:false}).limit(900),
        invoke({action:"staff"}).catch(()=>({staff:[]})),
        (supabase as any).from("adminos_whatsapp_templates").select("*").order("created_at",{ascending:true}),
      ]);
      if(tr.error||mr.error||tar.error)throw tr.error||mr.error||tar.error;
      const rawThreads=(tr.data||[]) as Thread[];const rawMessages=(mr.data||[]) as Message[];const staffRows=(sr.staff||[]) as Staff[];const staffMap=new Map(staffRows.map((s)=>[s.id,s]));
      const ids=Array.from(new Set(rawThreads.map((t)=>t.contact_id).filter(Boolean))) as string[];const contacts=new Map<string,Contact>();
      if(ids.length){const cr=await (supabase as any).from("adminos_contacts").select("id,profile_user_id,full_name,email,phone,student_number,campus,contact_type,metadata").in("id",ids);if(cr.error)throw cr.error;const profileIds=Array.from(new Set((cr.data||[]).map((c:any)=>c.profile_user_id).filter(Boolean))) as string[];const avatars=new Map<string,string|null>();if(profileIds.length){const pr=await (supabase as any).from("profiles").select("id,profile_picture_url").in("id",profileIds);for(const p of pr.data||[])avatars.set(p.id,p.profile_picture_url||null);}for(const c of cr.data||[])contacts.set(c.id,{...c,profile_picture_url:c.profile_user_id?avatars.get(c.profile_user_id)||null:null});}
      const last=new Map<string,Message>();for(const m of rawMessages)if(!last.has(m.thread_id))last.set(m.thread_id,m);
      const hydrated=rawThreads.map((t)=>({...t,contact:t.contact_id?contacts.get(t.contact_id)||null:null,lastMessage:last.get(t.id)||null,assignee:t.assigned_to?staffMap.get(t.assigned_to)||null:null}));
      setThreads(hydrated);setStaff(staffRows);setTemplates(tar.data||[]);setSelectedId((current)=>current&&hydrated.some((t)=>t.id===current)?current:hydrated[0]?.id||null);
    }catch(error:any){toast.error(error?.message||"Could not load WhatsApp Desk");}finally{setLoading(false);}
  },[invoke]);

  const loadThread=useCallback(async(id:string)=>{
    try{
      const [mr,vr,nr]=await Promise.all([
        (supabase as any).from("adminos_whatsapp_messages").select("*").eq("thread_id",id).order("created_at",{ascending:true}).limit(1000),
        (supabase as any).from("adminos_whatsapp_media_files").select("*").eq("thread_id",id).order("created_at",{ascending:false}).limit(100),
        (supabase as any).from("adminos_whatsapp_notes").select("*").eq("thread_id",id).order("created_at",{ascending:false}).limit(30),
      ]);
      if(mr.error||vr.error||nr.error)throw mr.error||vr.error||nr.error;setMessages(mr.data||[]);setVault(vr.data||[]);setNotes(nr.data||[]);
      await (supabase as any).from("adminos_whatsapp_threads").update({unread_count:0,updated_at:new Date().toISOString()}).eq("id",id);
    }catch(error:any){toast.error(error?.message||"Could not load conversation");}
  },[]);

  useEffect(()=>{void loadDesk();},[loadDesk]);
  useEffect(()=>{if(selectedId)void loadThread(selectedId);else{setMessages([]);setVault([]);setNotes([]);}setComposer("");setAttachment(null);setTemplateKey("");setTemplateVars({});},[selectedId,loadThread]);
  useEffect(()=>{const channel=(supabase as any).channel("adminos-whatsapp-next-live").on("postgres_changes",{event:"*",schema:"public",table:"adminos_whatsapp_threads"},()=>void loadDesk()).on("postgres_changes",{event:"*",schema:"public",table:"adminos_whatsapp_messages"},(p:any)=>{void loadDesk();const id=p?.new?.thread_id||p?.old?.thread_id;if(id===selectedId)void loadThread(id);}).on("postgres_changes",{event:"*",schema:"public",table:"adminos_whatsapp_media_files"},(p:any)=>{const id=p?.new?.thread_id||p?.old?.thread_id;if(id===selectedId)void loadThread(id);}).subscribe((s:string)=>setLive(s==="SUBSCRIBED"));return()=>{void (supabase as any).removeChannel(channel);};},[loadDesk,loadThread,selectedId]);

  useEffect(()=>{if(!selectedTemplate)return;const next:Record<string,string>={};for(const v of selectedTemplate.variables||[])next[String(v)]=String(v).includes("name")?(selected?.contact?.full_name||""):"";setTemplateVars(next);},[selectedTemplate,selected]);

  const visible=useMemo(()=>threads.filter((t)=>{const mode=t.mode||"ai_auto";if(filter==="unread"&&!Number(t.unread_count||0))return false;if(filter!=="all"&&filter!=="unread"&&mode!==filter&&!(filter==="escalated"&&t.status==="escalated"))return false;const q=search.trim().toLowerCase();if(!q)return true;return[t.contact?.full_name,t.contact?.email,t.contact?.student_number,t.channel_address,t.lastMessage?.body_text].filter(Boolean).join(" ").toLowerCase().includes(q);}),[threads,filter,search]);
  const unread=threads.reduce((n,t)=>n+Number(t.unread_count||0),0);
  const run=async(key:string,fn:()=>Promise<any>,success?:string)=>{setWorking(key);try{const result=await fn();if(success)toast.success(success);await Promise.all([loadDesk(),selectedId?loadThread(selectedId):Promise.resolve()]);return result;}catch(error:any){toast.error(error?.message||"Action failed");return null;}finally{setWorking(null);}};

  const setMode=async(mode:Mode)=>{if(selected)await run(`mode:${mode}`,()=>invoke({action:"set_mode",thread_id:selected.id,mode}),`${modeLabel(mode)} enabled`);};
  const assign=async(value:string)=>{if(selected)await run("assign",()=>invoke({action:"assign",thread_id:selected.id,assigned_to:value==="unassigned"?null:value}),"Assignment updated");};
  const addNote=async()=>{if(!selected||!note.trim())return;const body=note.trim();const result=await run("note",()=>invoke({action:"note",thread_id:selected.id,body}),"Private note saved");if(result)setNote("");};
  const makeDraft=async()=>{if(!selected)return;const result=await run("draft",()=>invoke({action:"ai_draft",thread_id:selected.id}),"Dimpho prepared a reply");if(result?.draft?.body_text)setComposer(result.draft.body_text);};
  const upload=async()=>{if(!attachment||!selected)return null;if(attachment.size>20*1024*1024)throw new Error("Attachment must be 20MB or smaller");const auth=await supabase.auth.getUser();if(!auth.data.user)throw new Error("Session expired");const safe=attachment.name.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-120);const path=`${auth.data.user.id}/${selected.id}/${Date.now()}-${safe}`;const result=await supabase.storage.from("adminos-whatsapp-media").upload(path,attachment,{upsert:false,contentType:attachment.type||undefined});if(result.error)throw result.error;return path;};
  const send=async()=>{if(!selected)return;await run("send",async()=>{const mediaPath=attachment?await upload():null;const result=await invoke({action:"send",thread_id:selected.id,body_text:composer,template_key:templateKey||null,template_vars:templateVars,media_path:mediaPath,media_name:attachment?.name||null,media_type:attachment?.type||null});setComposer("");setAttachment(null);setTemplateKey("");setTemplateVars({});return result;},"Message sent");};

  return <div className="space-y-4">
    <section className="relative overflow-hidden rounded-[32px] border bg-gradient-to-br from-background via-background to-emerald-500/[.07] p-5 shadow-[0_28px_90px_-58px_rgba(0,0,0,.6)] sm:p-6">
      <div className="pointer-events-none absolute -right-20 -top-24 h-72 w-72 rounded-full bg-emerald-500/10 blur-3xl" />
      <div className="relative flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex items-start gap-4"><Avatar className="h-14 w-14 rounded-[19px] bg-white shadow-lg"><AvatarImage src="/icon-512.png" className="object-cover"/><AvatarFallback>RK</AvatarFallback></Avatar><div><div className="flex flex-wrap gap-2"><Badge className="rounded-full gap-1.5"><MessageCircle className="h-3.5 w-3.5"/> WhatsApp Command</Badge><Badge variant="outline" className="rounded-full">Dimpho + Human</Badge><Badge variant="outline" className="rounded-full gap-1"><span className={cn("h-2 w-2 rounded-full",live?"bg-emerald-500":"bg-amber-500")}/>{live?"Live sync":"Connecting"}</Badge></div><h2 className="mt-3 text-2xl font-black tracking-tight sm:text-3xl">Premium service desk</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-muted-foreground">One inbox for real-time WhatsApp, AI assistance, staff takeover, secure images and document storage. Customer media is archived into the private AdminOS vault instead of relying on temporary Twilio URLs.</p></div></div><Button variant="outline" className="w-fit rounded-full" onClick={()=>void loadDesk()} disabled={loading}><RefreshCw className={cn("h-4 w-4",loading&&"animate-spin")}/>Refresh</Button></div>
    </section>

    <div className="grid min-h-[760px] overflow-hidden rounded-[32px] border bg-background shadow-[0_30px_90px_-58px_rgba(0,0,0,.5)] md:grid-cols-[320px_minmax(0,1fr)] xl:grid-cols-[340px_minmax(0,1fr)_330px]">
      <aside className={cn("min-w-0 flex-col border-r bg-muted/20 md:flex",mobileChat?"hidden":"flex")}>
        <div className="border-b bg-background/85 p-4 backdrop-blur-2xl"><div className="flex items-center justify-between"><div><p className="font-black">Inbox</p><p className="text-xs text-muted-foreground">{threads.length} conversations · {unread} unread</p></div><Inbox className="h-5 w-5"/></div><div className="relative mt-3"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="rounded-2xl border-0 bg-muted/70 pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search students, numbers, messages"/></div><div className="mt-3 flex gap-1 overflow-x-auto">{filters.map((f)=><button key={f} onClick={()=>setFilter(f)} className={cn("whitespace-nowrap rounded-full px-3 py-1.5 text-[11px] font-bold",filter===f?"bg-foreground text-background":"bg-muted text-muted-foreground")}>{f==="all"?"All":f==="unread"?"Unread":modeLabel(f)}</button>)}</div></div>
        <ScrollArea className="h-[650px] flex-1"><div className="p-2">{visible.map((t)=><ThreadRow key={t.id} thread={t} selected={t.id===selectedId} onClick={()=>{setSelectedId(t.id);setMobileChat(true);}}/>)}{!visible.length&&!loading&&<div className="p-10 text-center text-xs text-muted-foreground">No conversations match this view.</div>}</div></ScrollArea>
      </aside>

      <main className={cn("min-w-0 flex-col bg-gradient-to-b from-muted/10 to-background md:flex",mobileChat?"flex":"hidden")}>
        {selected?<><header className="border-b bg-background/85 p-3 backdrop-blur-2xl sm:p-4"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" className="rounded-full md:hidden" onClick={()=>setMobileChat(false)}><ArrowLeft className="h-5 w-5"/></Button><ContactAvatar thread={selected}/><div className="min-w-0"><p className="truncate font-black">{displayName(selected)}</p><p className="truncate text-xs text-muted-foreground">{phone(selected.channel_address)} · {selected.assignee?.full_name||"Unassigned"}</p></div></div><Badge variant={windowOpen?"default":"outline"} className="rounded-full">{windowOpen?"Service window":"Template required"}</Badge></div><div className="mt-3 flex w-fit rounded-full border bg-muted/60 p-1">{(["ai_auto","assist","human"] as Mode[]).map((m)=><button key={m} onClick={()=>void setMode(m)} className={cn("rounded-full px-3 py-1.5 text-[11px] font-bold",(selected.mode||"ai_auto")===m?"bg-background shadow-sm":"text-muted-foreground")}>{modeLabel(m)}</button>)}</div></header>
        <ScrollArea className="h-[510px] flex-1"><div className="mx-auto flex min-h-full max-w-4xl flex-col justify-end px-4 py-6"><div className="mb-5 flex justify-center"><span className="rounded-full border bg-background/80 px-3 py-1 text-[10px] text-muted-foreground"><ShieldCheck className="mr-1 inline h-3 w-3"/>Private media archive · AI/human audit trail</span></div>{messages.map((m)=><MessageBubble key={m.id} message={m}/>)}{!messages.length&&<div className="py-24 text-center text-sm text-muted-foreground">No messages yet.</div>}</div></ScrollArea>
        <div className="border-t bg-background/90 p-3 backdrop-blur-2xl"><div className="mx-auto max-w-4xl space-y-2"><div className="flex gap-1.5 overflow-x-auto"><button onClick={()=>void makeDraft()} className="rounded-full border px-3 py-1.5 text-[11px] font-bold"><Sparkles className="mr-1 inline h-3 w-3"/>Draft with Dimpho</button><button onClick={()=>setComposer("Thanks — I’m checking this for you now.")} className="rounded-full border px-3 py-1.5 text-[11px] font-bold">Checking now</button><button onClick={()=>setComposer("Your update has been received. I’ll guide you through the next step.")} className="rounded-full border px-3 py-1.5 text-[11px] font-bold">Next step</button></div>
          <div className="rounded-[24px] border bg-muted/35 p-2">{attachment&&<div className="mb-2 flex items-center justify-between rounded-2xl border bg-background px-3 py-2"><div className="min-w-0"><p className="truncate text-xs font-bold">{attachment.name}</p><p className="text-[9px] text-muted-foreground">Secure upload · {(attachment.size/1024/1024).toFixed(2)} MB</p></div><Button variant="ghost" size="icon" className="h-8 w-8 rounded-full" onClick={()=>setAttachment(null)}><X className="h-3.5 w-3.5"/></Button></div>}
          {!windowOpen&&<div className="mb-2"><Select value={templateKey||"none"} onValueChange={(v)=>setTemplateKey(v==="none"?"":v)}><SelectTrigger className="rounded-xl bg-background"><SelectValue placeholder="Choose approved template"/></SelectTrigger><SelectContent><SelectItem value="none">Choose approved template</SelectItem>{templates.filter((t)=>t.status==="approved"&&t.content_sid).map((t)=><SelectItem key={t.id} value={t.template_key}>{t.display_name}</SelectItem>)}</SelectContent></Select></div>}
          {selectedTemplate&&(selectedTemplate.variables||[]).length>0&&<div className="mb-2 grid gap-2 sm:grid-cols-2">{selectedTemplate.variables.map((v:string)=><Input key={v} value={templateVars[v]||""} onChange={(e)=>setTemplateVars((cur)=>({...cur,[v]:e.target.value}))} placeholder={v.replaceAll("_"," ")} className="rounded-xl bg-background"/>)}</div>}
          <Textarea value={composer} onChange={(e)=>setComposer(e.target.value)} disabled={!windowOpen&&!templateKey} placeholder={windowOpen?"Message…":"Choose an approved template to reopen the conversation"} className="min-h-[72px] resize-none border-0 bg-transparent shadow-none focus-visible:ring-0"/><div className="flex items-center justify-between border-t pt-2"><div className="flex gap-1"><input ref={fileRef} type="file" className="hidden" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,.docx" onChange={(e)=>setAttachment(e.target.files?.[0]||null)}/><Button variant="ghost" size="icon" className="rounded-full" disabled={!windowOpen} onClick={()=>fileRef.current?.click()}><Paperclip className="h-4 w-4"/></Button></div><Button className="rounded-full px-5" disabled={working==="send"||(!windowOpen&&!templateKey)||(!composer.trim()&&!attachment&&!templateKey)} onClick={()=>void send()}><Send className="h-4 w-4"/>Send</Button></div></div></div></div></>:
        <div className="grid min-h-[760px] place-items-center p-8 text-center"><div><MessageCircle className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-black">Select a conversation</p><p className="mt-1 text-xs text-muted-foreground">Dimpho and your staff share the same conversation history.</p></div></div>}
      </main>

      <aside className="hidden min-w-0 border-l bg-muted/15 xl:block"><ScrollArea className="h-[760px]"><div className="space-y-4 p-4">{selected?<><div className="text-center"><ContactAvatar thread={selected} large/><p className="mt-3 font-black">{displayName(selected)}</p><p className="text-xs text-muted-foreground">{selected.contact?.contact_type||"WhatsApp contact"}</p></div><ContextCard title="Customer"><Detail label="Email" value={selected.contact?.email}/><Detail label="Student no." value={selected.contact?.student_number}/><Detail label="Campus" value={selected.contact?.campus}/><Detail label="Phone" value={phone(selected.channel_address)}/></ContextCard><ContextCard title="Operations"><Select value={selected.assigned_to||"unassigned"} onValueChange={(v)=>void assign(v)}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Assign staff"/></SelectTrigger><SelectContent><SelectItem value="unassigned">Unassigned</SelectItem>{staff.map((s)=><SelectItem key={s.id} value={s.id}>{s.full_name||s.email||"Staff"}</SelectItem>)}</SelectContent></Select><p className="mt-3 text-xs leading-5 text-muted-foreground">{selected.last_summary||"Dimpho summaries and handoff context remain attached to this conversation."}</p></ContextCard><ContextCard title={`Secure media vault · ${vault.length}`}><MediaVault files={vault}/></ContextCard><ContextCard title="Internal notes"><div className="flex gap-2"><Input value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Private note" className="rounded-xl"/><Button size="sm" className="rounded-xl" onClick={()=>void addNote()}>Save</Button></div><div className="mt-3 space-y-2">{notes.slice(0,4).map((n)=><div key={n.id} className="rounded-xl bg-muted/60 p-2 text-xs">{n.body}</div>)}</div></ContextCard></>:<p className="text-sm text-muted-foreground">Select a conversation.</p>}</div></ScrollArea></aside>
    </div>
  </div>;
}

function ThreadRow({thread,selected,onClick}:{thread:Thread;selected:boolean;onClick:()=>void}){const unread=Number(thread.unread_count||0);return <button onClick={onClick} className={cn("mb-1 flex w-full items-center gap-3 rounded-[20px] p-3 text-left",selected?"bg-background shadow-sm ring-1 ring-black/5":"hover:bg-background/70")}><ContactAvatar thread={thread}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className={cn("truncate text-sm",unread?"font-black":"font-semibold")}>{displayName(thread)}</p><span className="text-[9px] text-muted-foreground">{when(thread.last_message_at)}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{thread.lastMessage?.body_text||"New conversation"}</p><div className="mt-2 flex items-center gap-2"><Badge variant="outline" className="h-5 rounded-full px-2 text-[9px]">{modeLabel(thread.mode||"ai_auto")}</Badge>{unread>0&&<span className="grid min-h-5 min-w-5 place-items-center rounded-full bg-emerald-500 px-1 text-[9px] font-bold text-white">{unread}</span>}</div></div></button>;}
function ContactAvatar({thread,large=false}:{thread:Thread;large?:boolean}){const name=displayName(thread);return <Avatar className={cn("bg-muted ring-1 ring-black/5",large?"mx-auto h-20 w-20":"h-11 w-11")}><AvatarImage src={thread.contact?.profile_picture_url||thread.contact?.metadata?.avatar_url||undefined} className="object-cover"/><AvatarFallback className="font-black">{initials(name)}</AvatarFallback></Avatar>;}
function displayName(thread:Thread){return thread.contact?.full_name||thread.lastMessage?.metadata?.profile_name||phone(thread.channel_address)||"WhatsApp contact";}
function MessageBubble({message}:{message:Message}){const outbound=message.direction==="outbound";const author=message.metadata?.author_type||(outbound?"human":"contact");return <div className={cn("mb-2 flex",outbound?"justify-end":"justify-start")}><div className="max-w-[86%] sm:max-w-[74%]">{outbound&&<div className="mb-1 flex justify-end"><span className={cn("rounded-full px-2 py-0.5 text-[9px] font-bold",author==="ai"?"bg-violet-500/10 text-violet-700":"bg-sky-500/10 text-sky-700")}>{author==="ai"?"Dimpho AI":"Staff"}</span></div>}<div className={cn("rounded-[22px] p-3 shadow-sm",outbound?"rounded-br-md bg-foreground text-background":"rounded-bl-md border bg-background")}>{message.body_text&&<p className="whitespace-pre-wrap break-words text-sm leading-5">{message.body_text}</p>}{Array.isArray(message.media)&&message.media.length>0&&<div className="mt-2 space-y-2">{message.media.map((item,i)=><MediaItem key={i} item={item} outbound={outbound}/>)}</div>}<div className={cn("mt-1.5 flex items-center justify-end gap-1 text-[9px]",outbound?"text-background/60":"text-muted-foreground")}>{when(message.sent_at||message.received_at||message.created_at)}{outbound&&<Delivery status={String(message.status||"sent")}/>}</div></div></div></div>;}
function MediaItem({item,outbound}:{item:any;outbound:boolean}){const [url,setUrl]=useState<string|null>(null);const [busy,setBusy]=useState(false);const isImage=String(item?.content_type||"").startsWith("image/");const open=async(download=false)=>{if(!item?.storage_path)return;setBusy(true);try{const bucket=item.storage_bucket||"adminos-whatsapp-media";const result=await supabase.storage.from(bucket).createSignedUrl(item.storage_path,3600,download?{download:item.name||"attachment"}:undefined);if(result.error)throw result.error;if(download){window.open(result.data.signedUrl,"_blank","noopener,noreferrer");}else setUrl(result.data.signedUrl);}catch(error:any){toast.error(error?.message||"Could not open attachment");}finally{setBusy(false);}};useEffect(()=>{if(isImage&&item?.storage_path)void open(false);},[item?.storage_path]);if(!item?.storage_path)return <div className={cn("rounded-xl px-3 py-2 text-[10px]",outbound?"bg-background/10":"bg-muted")}><ShieldCheck className="mr-1 inline h-3 w-3"/>Securing attachment…</div>;return <div className={cn("overflow-hidden rounded-xl border",outbound?"border-background/15 bg-background/10":"bg-muted/40")}>{isImage&&url&&<img src={url} alt={item.name||"WhatsApp image"} className="max-h-64 w-full object-cover"/>}<div className="flex items-center gap-2 p-2.5">{isImage?<ImageIcon className="h-4 w-4"/>:<FileText className="h-4 w-4"/>}<span className="min-w-0 flex-1 truncate text-[10px] font-semibold">{item.name||item.content_type||"Attachment"}</span><Button type="button" variant="ghost" size="icon" className="h-7 w-7 rounded-full" disabled={busy} onClick={()=>void open(true)}><Download className="h-3.5 w-3.5"/></Button></div></div>;}
function MediaVault({files}:{files:VaultFile[]}){if(!files.length)return <p className="text-xs text-muted-foreground">No archived files in this conversation yet.</p>;return <div className="space-y-2">{files.slice(0,12).map((f)=><VaultRow key={f.id} file={f}/>)}</div>;}
function VaultRow({file}:{file:VaultFile}){const download=async()=>{const result=await supabase.storage.from(file.storage_bucket).createSignedUrl(file.storage_path,3600,{download:file.original_name||"attachment"});if(result.error){toast.error(result.error.message);return;}window.open(result.data.signedUrl,"_blank","noopener,noreferrer");};return <div className="flex items-center gap-2 rounded-xl border bg-background p-2"><div className="grid h-8 w-8 place-items-center rounded-xl bg-muted">{String(file.content_type||"").startsWith("image/")?<ImageIcon className="h-3.5 w-3.5"/>:<FileText className="h-3.5 w-3.5"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-bold">{file.original_name||"Attachment"}</p><p className="text-[9px] text-muted-foreground">{file.content_type||"file"}</p></div><Button variant="ghost" size="icon" className="h-8 w-8 rounded-full" onClick={()=>void download()}><Download className="h-3.5 w-3.5"/></Button></div>;}
function ContextCard({title,children}:{title:string;children:any}){return <div className="rounded-[20px] border bg-background/75 p-4 shadow-sm"><p className="mb-3 text-[10px] font-black uppercase tracking-[.13em] text-muted-foreground">{title}</p>{children}</div>;}
function Detail({label,value}:{label:string;value:any}){return <div className="flex justify-between gap-3 border-b py-2 last:border-0"><span className="text-xs text-muted-foreground">{label}</span><span className="max-w-[60%] break-words text-right text-xs font-semibold">{String(value||"—")}</span></div>;}
function Delivery({status}:{status:string}){if(["delivered","read"].includes(status))return <CheckCheck className={cn("h-3 w-3",status==="read"&&"text-sky-300")}/>;if(["sent","queued","sending"].includes(status))return <Check className="h-3 w-3"/>;if(["failed","undelivered"].includes(status))return <CircleAlert className="h-3 w-3"/>;return null;}
