import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Building2, CalendarClock, CheckCircle2, FileText, GraduationCap, Mail, MapPin, MessageCircle, Phone, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { ScrollArea } from "@/components/ui/scroll-area";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

type Props={contactId:string|null;open:boolean;onClose:()=>void};
const when=(v?:string|null)=>v?new Date(v).toLocaleString("en-ZA",{dateStyle:"medium",timeStyle:"short"}):"—";
const eventIcon=(type:string)=>type.includes("whatsapp")?MessageCircle:type.includes("application")?FileText:type.includes("reservation")||type.includes("residence")?Building2:type.includes("wil")?GraduationCap:Activity;

export default function AdminOSCustomer360({contactId,open,onClose}:Props){
  const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);
  useEffect(()=>{if(!open||!contactId)return;let live=true;(async()=>{setLoading(true);const{data:payload,error}=await(supabase as any).rpc("adminos_customer_360",{p_contact_id:contactId});if(!live)return;if(error){toast.error(error.message||"Could not load Customer 360");setData(null);}else setData(payload||null);setLoading(false);})();return()=>{live=false;};},[contactId,open]);
  const contact=data?.contact||{},profile=data?.profile||{};const apps=Array.isArray(data?.applications)?data.applications:[];const timeline=Array.isArray(data?.timeline)?data.timeline:[];const actions=Array.isArray(data?.next_best_actions)?data.next_best_actions:[];const recovery=Array.isArray(data?.service_recovery)?data.service_recovery:[];
  const latest=apps[0]||null;const health=Number(latest?.health?.score||0);const healthBand=latest?.health?.health_band||"not scored";
  const identityTitle=contact.full_name||profile.full_name||contact.email||contact.phone||"Customer";
  const stats=useMemo(()=>[
    {label:"Timeline",value:timeline.length,icon:Activity},
    {label:"Next actions",value:actions.length,icon:Sparkles},
    {label:"Open recovery",value:recovery.length,icon:ShieldCheck},
    {label:"Applications",value:apps.length,icon:FileText},
  ],[timeline.length,actions.length,recovery.length,apps.length]);
  return <Sheet open={open} onOpenChange={(v)=>{if(!v)onClose();}}><SheetContent side="right" className="w-full overflow-hidden p-0 sm:max-w-2xl lg:max-w-3xl">
    <div className="border-b bg-gradient-to-br from-background to-violet-500/[.06] p-5 sm:p-6"><SheetHeader><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-primary/10"><UserRound className="h-5 w-5 text-primary"/></div><div className="min-w-0"><SheetTitle className="truncate text-2xl font-black">{identityTitle}</SheetTitle><SheetDescription>Universal Customer 360 · deterministic operational timeline</SheetDescription><div className="mt-2 flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full">{contact.contact_type||"person"}</Badge>{contact.campus&&<Badge variant="outline" className="rounded-full">{contact.campus}</Badge>}{contact.student_number&&<Badge variant="outline" className="rounded-full">#{contact.student_number}</Badge>}</div></div></div></SheetHeader></div>
    <ScrollArea className="h-[calc(100vh-132px)]"><div className="space-y-5 p-4 sm:p-6">
      {loading&&<div className="rounded-3xl border border-dashed p-10 text-center text-sm text-muted-foreground">Loading live Customer 360…</div>}
      {!loading&&data&&<>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{stats.map(x=><div key={x.label} className="rounded-2xl border bg-muted/20 p-3"><x.icon className="h-4 w-4 text-muted-foreground"/><p className="mt-3 text-xl font-black">{x.value}</p><p className="text-[10px] text-muted-foreground">{x.label}</p></div>)}</div>
        <section className="grid gap-3 md:grid-cols-2">
          <div className="rounded-[24px] border p-4"><p className="text-xs font-black uppercase tracking-[.12em] text-muted-foreground">Identity</p><div className="mt-3 space-y-2 text-sm">{contact.phone&&<Line icon={Phone} text={contact.phone}/>} {contact.email&&<Line icon={Mail} text={contact.email}/>} {contact.campus&&<Line icon={MapPin} text={contact.campus}/>} {profile.course&&<Line icon={GraduationCap} text={profile.course}/>}</div></div>
          <div className="rounded-[24px] border p-4"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-[.12em] text-muted-foreground">Latest application health</p><Badge variant="outline" className={cn("rounded-full",health>=85&&"border-emerald-500/30 text-emerald-700",health<70&&latest&&"border-amber-500/30 text-amber-700")}>{latest?`${health}%`:`No application`}</Badge></div>{latest?<><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,Math.max(0,health))}%`}}/></div><p className="mt-2 text-sm font-black capitalize">{String(healthBand).replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted-foreground">{latest.application?.status||"Unknown status"}{latest.residence?.name?` · ${latest.residence.name}`:""}</p>{latest.health?.missing_items?.length>0&&<p className="mt-2 text-xs text-amber-700">Needs: {(latest.health.missing_items as string[]).join(", ")}</p>}</>:<p className="mt-4 text-sm text-muted-foreground">No accommodation application is currently linked to this profile.</p>}</div>
        </section>
        <section className="rounded-[26px] border p-4"><div className="flex items-center justify-between"><div><p className="font-black">Next best actions</p><p className="text-xs text-muted-foreground">Database-ranked actions. No AI credit used.</p></div><Sparkles className="h-5 w-5 text-violet-500"/></div>{actions.length?<div className="mt-3 space-y-2">{actions.slice(0,8).map((a:any)=><div key={a.id} className="flex items-start gap-3 rounded-2xl bg-muted/30 p-3"><div className={cn("mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-xl",Number(a.priority)>=90?"bg-red-500/10 text-red-600":"bg-primary/10 text-primary")}><CalendarClock className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="text-sm font-black">{a.title||a.action_type?.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted-foreground">{a.rationale||a.description||"Recommended next service action"}</p></div><Badge variant="outline" className="rounded-full text-[9px]">P{a.priority||0}</Badge></div>)}</div>:<div className="mt-3 flex items-center gap-2 rounded-2xl bg-emerald-500/5 p-3 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4"/>No outstanding next-best action.</div>}</section>
        {recovery.length>0&&<section className="rounded-[26px] border border-amber-500/30 bg-amber-500/[.04] p-4"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-600"/><p className="font-black">Service recovery</p></div><div className="mt-3 space-y-2">{recovery.map((r:any)=><div key={r.id} className="rounded-2xl bg-background p-3"><p className="text-sm font-bold capitalize">{String(r.issue_type||"service issue").replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted-foreground">Priority {r.priority} · detected {when(r.last_detected_at)}</p></div>)}</div></section>}
        <section className="rounded-[26px] border p-4"><div><p className="font-black">Customer timeline</p><p className="text-xs text-muted-foreground">Applications, reservations, documents, WIL, enquiries and WhatsApp in one ledger.</p></div>{timeline.length?<div className="mt-4 space-y-1">{timeline.map((e:any)=>{const Icon=eventIcon(String(e.event_type||e.source_type||""));return <div key={e.id} className="relative flex gap-3 pb-4"><div className="relative z-10 grid h-9 w-9 shrink-0 place-items-center rounded-2xl border bg-background"><Icon className="h-4 w-4"/></div><div className="min-w-0 flex-1 border-b pb-3"><div className="flex items-start justify-between gap-3"><p className="text-sm font-black capitalize">{String(e.title||e.event_type||e.source_type||"Activity").replaceAll("_"," ")}</p><span className="shrink-0 text-[9px] text-muted-foreground">{when(e.occurred_at)}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{e.description||e.summary||e.metadata?.status||e.source_table||"ResKonnect activity"}</p></div></div>})}</div>:<p className="mt-3 text-sm text-muted-foreground">No timeline events recorded yet.</p>}</section>
      </>}
      {!loading&&!data&&<div className="rounded-3xl border border-dashed p-10 text-center"><UserRound className="mx-auto h-7 w-7 text-muted-foreground"/><p className="mt-3 font-black">Customer record unavailable</p><p className="mt-1 text-xs text-muted-foreground">The selected contact could not be loaded.</p><Button variant="outline" className="mt-4" onClick={onClose}>Close</Button></div>}
    </div></ScrollArea>
  </SheetContent></Sheet>;
}
function Line({icon:Icon,text}:{icon:any;text:string}){return <div className="flex items-center gap-2"><Icon className="h-3.5 w-3.5 text-muted-foreground"/><span className="truncate">{text}</span></div>;}
