import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Building2, CheckCircle2, ExternalLink, Image as ImageIcon, MapPin, RefreshCw, Sparkles, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

type ResidenceReady = {
  id:string; name:string; slug?:string|null; campus?:string|null; city?:string|null; address?:string|null;
  price?:number|null; private_price?:number|null; nsfas_price?:number|null; available_spots?:number|null;
  primary_image_url?:string|null; gallery_image_count?:number; has_image:boolean; has_price:boolean; has_location:boolean;
  has_availability:boolean; has_public_link:boolean; has_audience:boolean; readiness_score:number; missing_fields?:string[]|null; updated_at:string;
};
type Filter="all"|"ready"|"images"|"rent"|"location"|"availability";

export default function AdminOSResidenceReadiness(){
  const [rows,setRows]=useState<ResidenceReady[]>([]);const[loading,setLoading]=useState(true);const[filter,setFilter]=useState<Filter>("all");const[search,setSearch]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const result=await (supabase as any).from("adminos_residence_readiness_v").select("*").order("readiness_score",{ascending:true}).order("name",{ascending:true}).limit(1000);if(result.error)throw result.error;setRows(result.data||[]);}catch(error:any){toast.error(error?.message||"Could not load residence readiness");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();const channel=(supabase as any).channel("adminos-residence-readiness-live").on("postgres_changes",{event:"*",schema:"public",table:"residences"},()=>void load()).subscribe();return()=>{void (supabase as any).removeChannel(channel);};},[load]);
  const total=rows.length;const ready=rows.filter((r)=>r.readiness_score>=90&&r.has_image&&r.has_price&&r.has_location&&r.has_public_link).length;const missingImages=rows.filter((r)=>!r.has_image).length;const missingRent=rows.filter((r)=>!r.has_price).length;const missingLocation=rows.filter((r)=>!r.has_location).length;const missingAvailability=rows.filter((r)=>!r.has_availability).length;const score=total?Math.round(rows.reduce((sum,r)=>sum+Number(r.readiness_score||0),0)/total):0;
  const visible=useMemo(()=>rows.filter((r)=>{if(filter==="ready"&&!(r.readiness_score>=90&&r.has_image))return false;if(filter==="images"&&r.has_image)return false;if(filter==="rent"&&r.has_price)return false;if(filter==="location"&&r.has_location)return false;if(filter==="availability"&&r.has_availability)return false;const q=search.trim().toLowerCase();return !q||[r.name,r.campus,r.city,r.address].filter(Boolean).join(" ").toLowerCase().includes(q);}),[rows,filter,search]);
  const topNeed=missingImages>0?`${missingImages} published residences still need a usable image`:missingAvailability>0?`${missingAvailability} residences need an availability value`:"The published residence catalogue is structurally ready";

  return <div className="space-y-5">
    <section className="relative overflow-hidden rounded-[30px] border bg-gradient-to-br from-background via-background to-violet-500/[.06] p-5 shadow-sm sm:p-6"><div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap gap-2"><Badge className="rounded-full gap-1.5"><Sparkles className="h-3.5 w-3.5"/> Dimpho Residence Setup</Badge><Badge variant="outline" className="rounded-full">Live catalogue</Badge></div><h3 className="mt-3 text-2xl font-black tracking-tight">Make every residence WhatsApp-ready.</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Dimpho reads the live residence records at reply time. When an admin adds a new image, changes rent, updates location or availability, the next accommodation response uses the new data automatically — no separate WhatsApp catalogue sync is required.</p></div><Button variant="outline" className="w-fit rounded-full" onClick={()=>void load()} disabled={loading}><RefreshCw className={cn("h-4 w-4",loading&&"animate-spin")}/>Refresh readiness</Button></div>
      <div className="relative mt-5 rounded-[22px] border bg-background/75 p-4 backdrop-blur"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-violet-500/10 text-violet-700"><Sparkles className="h-4 w-4"/></div><div><p className="font-black">Dimpho setup brief</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{topNeed}. Rent and location coverage are checked separately so Dimpho never needs to invent a property fact. Prioritize the lowest-readiness residences below, then complete them in Accommodation Operations.</p></div></div></div>
    </section>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={Building2} label="Published" value={total}/><Metric icon={CheckCircle2} label="WhatsApp-ready" value={ready}/><Metric icon={ImageIcon} label="Missing images" value={missingImages} alert={missingImages>0}/><Metric icon={WalletCards} label="Missing rent" value={missingRent} alert={missingRent>0}/><Metric icon={MapPin} label="Missing location" value={missingLocation} alert={missingLocation>0}/><Metric icon={AlertTriangle} label="Availability gaps" value={missingAvailability} alert={missingAvailability>0}/></div>

    <div className="rounded-[28px] border bg-background p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="font-black">Catalogue readiness</p><span className="text-2xl font-black">{score}%</span></div><Progress value={score} className="mt-2 h-2"/><p className="mt-2 text-xs text-muted-foreground">Readiness is weighted toward images, rent, location, public links, audience data, availability and room type.</p></div><Button asChild className="rounded-full"><Link to="/admin/operations">Complete residence setups <ExternalLink className="h-4 w-4"/></Link></Button></div></div>

    <div className="rounded-[28px] border bg-background shadow-sm"><div className="border-b p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-black">Residence setup queue</p><p className="text-xs text-muted-foreground">Lowest readiness first. Changes refresh automatically.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search residence or campus" className="w-full rounded-xl sm:w-64"/><div className="flex gap-1 overflow-x-auto rounded-xl bg-muted p-1">{(["all","ready","images","rent","location","availability"] as Filter[]).map((f)=><button key={f} onClick={()=>setFilter(f)} className={cn("whitespace-nowrap rounded-lg px-2.5 py-1.5 text-[10px] font-bold",filter===f?"bg-background shadow-sm":"text-muted-foreground")}>{f==="all"?"All":f==="ready"?"Ready":`Missing ${f}`}</button>)}</div></div></div></div>
      <div className="divide-y">{visible.slice(0,120).map((r)=><ResidenceRow key={r.id} row={r}/>)}</div>{!visible.length&&!loading&&<div className="p-10 text-center text-sm text-muted-foreground">No residences match this filter.</div>}
    </div>
  </div>;
}

function Metric({icon:Icon,label,value,alert=false}:{icon:any;label:string;value:number;alert?:boolean}){return <div className="rounded-[22px] border bg-background p-4 shadow-sm"><div className="flex items-center justify-between"><div className={cn("grid h-9 w-9 place-items-center rounded-2xl",alert?"bg-amber-500/10 text-amber-700":"bg-muted")}><Icon className="h-4 w-4"/></div><span className="text-2xl font-black">{value}</span></div><p className="mt-3 text-xs font-black">{label}</p></div>;}
function ResidenceRow({row}:{row:ResidenceReady}){const missing=row.missing_fields||[];return <div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="h-16 w-20 shrink-0 overflow-hidden rounded-2xl border bg-muted">{row.primary_image_url?<img src={row.primary_image_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center"><ImageIcon className="h-5 w-5 text-muted-foreground/50"/></div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-black">{row.name}</p><Badge variant="outline" className={cn("rounded-full text-[9px]",row.readiness_score>=90?"border-emerald-500/20 bg-emerald-500/10 text-emerald-700":"border-amber-500/20 bg-amber-500/10 text-amber-700")}>{row.readiness_score}% ready</Badge></div><p className="mt-1 truncate text-xs text-muted-foreground">{[row.campus,row.city,row.address].filter(Boolean).slice(0,2).join(" · ")||"Location pending"}</p><div className="mt-2 flex flex-wrap gap-1.5">{missing.length?missing.map((m)=><span key={m} className="rounded-full bg-amber-500/10 px-2 py-1 text-[9px] font-bold text-amber-800">Needs {m.replaceAll("_"," ")}</span>):<span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[9px] font-bold text-emerald-700">Dimpho-ready</span>}</div></div><div className="text-left sm:text-right"><p className="text-xs font-bold">{row.price!=null?`R${Number(row.price).toLocaleString("en-ZA")}`:row.private_price!=null?`R${Number(row.private_price).toLocaleString("en-ZA")}`:row.nsfas_price!=null?`R${Number(row.nsfas_price).toLocaleString("en-ZA")}`:"Rent pending"}</p><p className="mt-1 text-[10px] text-muted-foreground">{row.available_spots==null?"Availability not set":`${row.available_spots} spots`}</p></div></div>;}
