import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import SEO from '@/components/SEO';
import DashboardLayout from '@/components/DashboardLayout';
import {Card,CardContent} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Input} from '@/components/ui/input';
import {supabase} from '@/integrations/supabase/client';

type Partner={id:string;kind:'application'|'residence';slug:string;display_name:string;bio:string;campus:string;bio_review:string;bio_verified_until:string|null};
const isVerified=(p:Partner)=>p.bio_review==='verified'&&Boolean(p.bio_verified_until&&Date.parse(p.bio_verified_until)>Date.now());
export default function PartnerDirectory(){const [all,setAll]=useState<Partner[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState<'all'|'application'|'residence'>('all'),[query,setQuery]=useState('');
 useEffect(()=>{let live=true;void(async()=>{const {data,error}=await(supabase as any).from('rk_partner_profiles').select('id,kind,slug,display_name,bio,campus,bio_review,bio_verified_until').eq('status','published').order('created_at',{ascending:false}).limit(250);if(!live)return;setAll((data||[]) as Partner[]);setError(error?.message||'');setLoading(false);})();return()=>{live=false;};},[]);
 const filtered=useMemo(()=>all.filter(p=>(filter==='all'||filter===p.kind)&&`${p.display_name} ${p.campus} ${p.bio}`.toLowerCase().includes(query.toLowerCase().trim())).sort((a,b)=>Number(isVerified(b))-Number(isVerified(a))||a.display_name.localeCompare(b.display_name)),[all,filter,query]);
 return <DashboardLayout><SEO title="Find verified application and residence partners | ResKonnect" description="Browse ResKonnect-approved student application partners and residence recruitment assistants by service and campus."/><main className="mx-auto max-w-6xl space-y-6 px-4 py-8"><section className="rounded-3xl bg-[#071326] p-7 text-white"><Badge className="bg-[#F5B32F] text-[#071326]">RESKONNECT · APPROVED PARTNERS</Badge><h1 className="mt-4 text-3xl font-black">Find a student assistance partner</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/75">Choose an application assistant for university or TVET applications, or a residence recruiter for accommodation. You can find partners here even if you have not arrived through their TikTok accounts.</p></section><nav className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link to="/application-assistance">My application assistance</Link></Button><Button variant="outline" asChild><Link to="/findmyres">Find accommodation</Link></Button></nav><div className="flex flex-wrap gap-2" aria-label="Filter partners">{(['all','application','residence'] as const).map(k=><Button key={k} type="button" variant={filter===k?'default':'outline'} onClick={()=>setFilter(k)}>{k==='all'?'All partners':k==='application'?'Application partners':'Residence recruiters'}</Button>)}</div><Input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Find a partner by name or campus" placeholder="Search by name, campus or assistance area"/>{loading?<p>Loading approved partners…</p>:error?<p role="alert">Unable to load the directory: {error}</p>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map(p=><Card key={p.id}><CardContent className="space-y-3 p-5"><div className="flex flex-wrap gap-2"><Badge>{p.kind==='application'?'Application assistance':'Residence recruitment'}</Badge>{isVerified(p)&&<Badge className="bg-emerald-600 text-white">Verified TikTok bio</Badge>}</div><h2 className="text-xl font-black">{p.display_name}</h2><p className="text-sm text-muted-foreground">{p.campus||'Campus or area not specified'}</p><p className="line-clamp-3 text-sm leading-6">{p.bio||'ResKonnect-approved student assistance partner.'}</p><Button asChild><Link to={'/partners/'+p.slug}>View profile and get assistance</Link></Button></CardContent></Card>)}{!filtered.length&&<p className="rounded-xl border border-dashed p-6 text-sm text-muted-foreground">No currently approved partner matches these filters. You may still use Find My Res or the ResKonnect applications service.</p>}</div>}</main></DashboardLayout>;
}
