import {useEffect,useMemo,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import SEO from '@/components/SEO';
import DashboardLayout from '@/components/DashboardLayout';
import PartnerIdentityPanel from '@/components/partners/PartnerIdentityPanel';
import PartnerApprovalConsole from '@/components/partners/PartnerApprovalConsole';
import {useAuth} from '@/contexts/AuthContext';
import {Badge} from '@/components/ui/badge';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Field,Panel,selectStyle} from '@/components/student-care/CareUI';
import {db,friendlyStatus,readAllPages} from '@/lib/studentCare';
import {toast} from 'sonner';

type PublicProfile={user_id:string;slug:string;display_name:string;bio:string;campus:string;status:string;bio_review:string;bio_verified_until:string|null;tiktok_url:string|null};
const verified=(p:PublicProfile)=>p.bio_review==='verified'&&Boolean(p.bio_verified_until&&Date.parse(p.bio_verified_until)>Date.now());
export default function ApplicationPartners(){
 const {user}=useAuth();const location=useLocation();const navigate=useNavigate();const partnerView=location.pathname==='/application-partners';
 const [partners,setPartners]=useState<any[]>([]),[publicProfiles,setPublicProfiles]=useState<PublicProfile[]>([]),[partner,setPartner]=useState<any>(null),[cases,setCases]=useState<any[]>([]),[submissions,setSubmissions]=useState<any[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[semester,setSemester]=useState('all'),[year,setYear]=useState('all');
 const [form,setForm]=useState({display_name:'',bio:'',assistance_fee:'0'});
 const load=async()=>{setLoading(true);setError('');try{
 const [active,profiles]=await Promise.all([db.from('creator_partners').select('id,user_id,slug,display_name,bio,assistance_fee,partner_kind').eq('status','active').order('display_name'),db.from('rk_partner_profiles').select('user_id,slug,display_name,bio,campus,status,bio_review,bio_verified_until,tiktok_url').eq('kind','application').eq('status','published')]);
 if(active.error||profiles.error)throw active.error||profiles.error;
 setPartners((active.data||[]).filter((p:any)=>p.partner_kind==='application'));setPublicProfiles((profiles.data||[]) as PublicProfile[]);
 if(!user){setCases([]);setSubmissions([]);setPartner(null);return;}
 const own=await db.from('creator_partners').select('*').eq('user_id',user.id).maybeSingle();if(own.error)throw own.error;setPartner(own.data);if(own.data)setForm({display_name:own.data.display_name,bio:own.data.bio||'',assistance_fee:String(own.data.assistance_fee)});
 if(partnerView&&(!own.data||own.data.status!=='active')){setCases([]);setSubmissions([]);return;}
 const rows=await readAllPages(()=>db.from('creator_assistance_cases').select('*').eq(partnerView?'creator_id':'student_user_id',partnerView?own.data.id:user.id).order('created_at',{ascending:false}));setCases(rows);
 const ids=rows.map((c:any)=>c.id);let found:any[]=[];for(let i=0;i<ids.length;i+=100){const r=await db.from('assistance_submissions').select('id,case_id,status,submitted_at').in('case_id',ids.slice(i,i+100));if(r.error)throw r.error;found=found.concat(r.data||[]);}setSubmissions(found);
 }catch(e:any){setError(e.message||'Could not load application assistance');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[user?.id,partnerView]);
 const visible=useMemo(()=>cases.filter((c:any)=>(semester==='all'||Number(c.intake_semester)===Number(semester))&&(year==='all'||Number(c.intake_year)===Number(year))&&[c.applicant_name,...(c.target_institutions||[]),c.status].join(' ').toLowerCase().includes(search.toLowerCase())),[cases,semester,year,search]);
 const sent=submissions.filter((s:any)=>visible.some((c:any)=>c.id===s.case_id)&&s.submitted_at).length;
 const directory=useMemo(()=>partners.map((p:any)=>({...p,publicProfile:publicProfiles.find(x=>x.user_id===p.user_id)})).sort((a:any,b:any)=>Number(Boolean(b.publicProfile&&verified(b.publicProfile)))-Number(Boolean(a.publicProfile&&verified(a.publicProfile)))||a.display_name.localeCompare(b.display_name)),[partners,publicProfiles]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!user)return;const fee=Number(form.assistance_fee);if(!Number.isFinite(fee)||fee<0||fee>100)return toast.error('Choose a fee between R0 and R100');setBusy(true);try{const p={display_name:form.display_name.trim(),bio:form.bio.trim(),assistance_fee:fee};const r=partner?await db.from('creator_partners').update(p).eq('id',partner.id).select('id').single():await db.from('creator_partners').insert({...p,user_id:user.id,slug:'application-'+user.id.slice(0,12),referral_code:'APP'+user.id.replaceAll('-','').slice(0,16).toUpperCase(),platform:'application_assistance',partner_kind:'application',status:'pending',follower_count:0});if(r.error)throw r.error;toast.success(partner?'Partner details saved':'Application partner request submitted for review');await load();}catch(e:any){toast.error(e.message);}finally{setBusy(false);}};
 return <DashboardLayout><SEO title={partnerView?'Application Partner Dashboard | ResKonnect':'Application Assistance Partners | ResKonnect'} description="Find approved university and TVET application assistants, choose a partner and track consented applications." noIndex={partnerView}/><main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6"><section className="rounded-3xl bg-[#071326] p-7 text-white sm:p-10"><Badge className="bg-[#F5B32F] text-[#071326]">RESKONNECT · OPPORTUNITY</Badge><h1 className="mt-4 text-3xl font-black sm:text-4xl">{partnerView?'Application Partner Command Centre':'Find your application partner'}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/75">Students can discover approved partners here or through TikTok. Each student chooses their partner and authorises an individual assistance case. The partner fee is capped at R100 for the annual case; any official institution application fee is separate.</p></section>
 <nav className="flex flex-wrap gap-2"><Button asChild variant={!partnerView?'default':'outline'}><Link to="/application-assistance">Find assistance / My cases</Link></Button><Button asChild variant={partnerView?'default':'outline'}><Link to="/application-partners">Partner dashboard</Link></Button><Button asChild variant="outline"><Link to="/apply">Explore institutions</Link></Button></nav>
 {error&&<p role="alert" className="rounded-xl border border-destructive p-4">{error}<Button className="ml-3" variant="outline" onClick={()=>void load()}>Retry</Button></p>}{!user&&<Button onClick={()=>navigate('/auth?returnTo='+encodeURIComponent(location.pathname))}>Sign in / Create account</Button>}
 {loading?<p className="py-12 text-center">Loading application workspace…</p>:<>
 {partnerView&&user&&<><Panel title={partner?'Your application-partner registration':'Become an application partner'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Partner / business name"><Input required minLength={2} maxLength={160} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></Field><Field label="Annual assistance fee (R0–R100)"><Input required type="number" min="0" max="100" step="0.01" value={form.assistance_fee} onChange={e=>setForm({...form,assistance_fee:e.target.value})}/></Field><Field label="Application experience and institutions you can assist with" wide><Textarea required maxLength={3000} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></Field><div className="flex flex-wrap items-center gap-3 sm:col-span-2"><Button disabled={busy}>{busy?'Saving…':partner?'Save registration':'Submit for approval'}</Button>{partner&&<Badge variant={partner.status==='active'?'default':'outline'}>{partner.status}</Badge>}</div></form><p className="text-xs text-muted-foreground">ResKonnect reviews your registration before students can select you. Your institution assignments require separate administrator approval.</p>{partner?.status==='active'&&<div className="flex gap-2"><Button variant="outline" onClick={()=>{void navigator.clipboard.writeText(window.location.origin+'/creator-assist/'+partner.slug).then(()=>toast.success('Intake link copied')).catch(()=>toast.error('Copy failed'));}}>Copy student intake link</Button><Button asChild variant="outline"><Link to={'/creator-assist/'+partner.slug}>Open intake</Link></Button></div>}</Panel>
 {partner&&<PartnerIdentityPanel kind="application" legacySlug={partner.slug} legacyName={partner.display_name}/>}</>}
 {!partnerView&&<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{directory.map((p:any)=><Panel key={p.id} title={p.publicProfile?.display_name||p.display_name}><div className="flex flex-wrap gap-2"><Badge>Approved application partner</Badge>{p.publicProfile&&verified(p.publicProfile)&&<Badge className="bg-emerald-600">Verified TikTok bio</Badge>}</div><p className="text-sm text-muted-foreground">{p.publicProfile?.bio||p.bio||'University and TVET application assistance.'}</p><p className="text-sm">{p.publicProfile?.campus||'Available to assist'}</p><p className="font-bold">{Number(p.assistance_fee)===0?'Free assistance':'R'+Number(p.assistance_fee).toFixed(2)+' per annual case'}</p><div className="flex flex-wrap gap-2">{p.publicProfile&&<Button asChild variant="outline"><Link to={'/partners/'+p.publicProfile.slug}>View public profile</Link></Button>}<Button asChild><Link to={'/creator-assist/'+p.slug}>Choose partner</Link></Button></div></Panel>)}{!directory.length&&<Panel title="Partner intake is open"><p className="text-sm">No approved application partners are listed yet.</p><Button asChild variant="outline"><Link to="/application-partners">Apply as a partner</Link></Button></Panel>}</div>}
 {user&&<Panel title={partnerView?'Assigned application cases':'My assistance cases'}><div className="grid gap-3 sm:grid-cols-3">{[['Cases in view',visible.length],['Institution applications sent',sent],['Awaiting documents',visible.filter((c:any)=>c.status==='documents_pending').length]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-muted/40 p-4"><p className="text-3xl font-black">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div>)}</div><div className="grid gap-3 sm:grid-cols-3"><Input aria-label="Search cases" placeholder="Student, institution or status" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Intake year" className={selectStyle} value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{[...new Set(cases.map((c:any)=>c.intake_year))].sort().map(y=><option key={y} value={y}>{y}</option>)}</select><select aria-label="Semester" className={selectStyle} value={semester} onChange={e=>setSemester(e.target.value)}><option value="all">All semesters</option><option value="1">First semester</option><option value="2">Second semester</option></select></div>{!visible.length&&<p className="py-6 text-sm text-muted-foreground">No matching cases. Students must choose a partner and grant case-specific access first.</p>}<div className="divide-y">{visible.map((c:any)=><Link key={c.id} to={'/application-assistance/case/'+c.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold">{c.applicant_name}</p><p className="text-sm text-muted-foreground">{(c.target_institutions||[]).join(', ')} · {c.intake_year} · Semester {c.intake_semester}</p><p className="mt-1 text-xs">Agreed annual fee: R{Number(c.service_fee).toFixed(2)}</p></div><Badge variant="secondary">{friendlyStatus(c.status)}</Badge></Link>)}</div></Panel>}
 </>}
 <PartnerApprovalConsole kind="application"/>
 </main></DashboardLayout>;
}
