import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "@/components/DashboardLayout";
import SEO from "@/components/SEO";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Building2, CheckCircle2, Clock, Copy, FileText, Link2, MapPin, MousePointer2, Search, Sparkles, Trophy, UserCheck, Wallet } from "lucide-react";
import { toast } from "sonner";
import { useRealtimeProfile } from "@/hooks/useRealtimeProfile";

export default function RecruiterDashboard(){
  const {user}=useAuth();const navigate=useNavigate();const {profile}=useRealtimeProfile(user);
  const [stats,setStats]=useState<any>(null);const [applicants,setApplicants]=useState<any[]>([]);const [residences,setResidences]=useState<any[]>([]);const [links,setLinks]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState("");const [selecting,setSelecting]=useState<string|null>(null);

  const load=useCallback(async()=>{if(!user)return;setLoading(true);const [{data:s},{data:a},{data:r},{data:l}]=await Promise.all([
    (supabase as any).from("recruiter_dashboard_v").select("*").eq("user_id",user.id).maybeSingle(),
    (supabase as any).from("recruiter_applicants_v").select("*").eq("referral_agent_user_id",user.id).order("referred_at",{ascending:false}),
    (supabase as any).from("recruitable_residences_v").select("*").order("data_quality_score",{ascending:false}).limit(150),
    (supabase as any).from("recruiter_residence_links").select("id,link_key,residence_id,referral_code,is_active,created_at,residences(name,slug,address,campus,image_url,cover_image_url,studio_image_url)").eq("recruiter_user_id",user.id).eq("is_active",true).order("created_at",{ascending:false}),
  ]);setStats(s||null);setApplicants(a||[]);setResidences(r||[]);setLinks(l||[]);setLoading(false);},[user]);
  useEffect(()=>{void load();},[load]);
  const genericLink=stats?.code?`${window.location.origin}/r/${stats.code}`:"";
  const copy=(text:string)=>{void navigator.clipboard.writeText(text);toast.success("Copied to clipboard");};
  const choose=async(residenceId:string)=>{setSelecting(residenceId);const {data,error}=await (supabase as any).rpc("recruiter_select_residence",{p_residence_id:residenceId});setSelecting(null);if(error)return toast.error(error.message||"Could not activate this residence campaign");const url=`${window.location.origin}/rr/${data.linkKey}`;copy(url);toast.success(`${data.residenceName} campaign activated`);await load();};
  const filtered=useMemo(()=>residences.filter((r)=>`${r.name||""} ${r.address||""} ${r.campus||""} ${r.city||""}`.toLowerCase().includes(search.toLowerCase())),[residences,search]);
  const selectedIds=new Set(links.map((x)=>x.residence_id));
  const approved=Number(stats?.approved_count||0);const bonusTarget=10;const bonusProgress=Math.min(100,(approved/bonusTarget)*100);
  if(loading)return <DashboardLayout><div className="p-8 text-center text-muted-foreground">Loading recruiter command centre…</div></DashboardLayout>;

  return <DashboardLayout><SEO title="Recruiter Dashboard | ResKonnect" description="Choose accommodation campaigns and track referrals, placements and commissions."/><div className="mx-auto max-w-7xl space-y-6 p-3 pb-24 sm:p-6 lg:p-8">
    <div className="flex flex-col gap-4 rounded-2xl border bg-card p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-primary/10"><Sparkles className="h-7 w-7 text-primary"/></div><div className="min-w-0"><h1 className="truncate text-2xl font-black">{profile?.full_name||"Recruiter"}</h1><div className="mt-1 flex flex-wrap gap-2"><Badge variant="outline">{stats?.code||"NO CODE"}</Badge>{stats?.status==="approved"?<Badge>Active recruiter</Badge>:<Badge variant="destructive">{stats?.status||"Pending"}</Badge>}</div></div></div>{stats?.badge_level&&<Badge className="self-start sm:self-auto"><Trophy className="mr-1.5 h-4 w-4"/>{String(stats.badge_level).toUpperCase()} RECRUITER</Badge>}</div>

    {!stats?<Card className="border-dashed"><CardContent className="p-10 text-center"><Clock className="mx-auto h-10 w-10 text-muted-foreground"/><h2 className="mt-3 text-xl font-bold">Verification pending</h2><p className="mt-2 text-sm text-muted-foreground">Your recruiter access is not active yet.</p><Button className="mt-4" onClick={()=>navigate("/recruit")}>View application status</Button></CardContent></Card>:<>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={MousePointer2} label="Clicks" value={stats.total_clicks}/><Metric icon={UserCheck} label="Signups" value={stats.total_signups}/><Metric icon={FileText} label="Applications" value={stats.total_applications}/><Metric icon={CheckCircle2} label="Approved placements" value={stats.approved_count}/></div>

      <Card className="overflow-hidden border-primary/20"><div className="border-b bg-primary/5 px-5 py-3"><h2 className="flex items-center gap-2 font-bold"><Link2 className="h-4 w-4"/>Platform referral link</h2></div><CardContent className="grid gap-4 p-5 md:grid-cols-2"><div className="space-y-1.5"><Label>Recruiter code</Label><div className="flex gap-2"><Input readOnly value={stats.code||""} className="font-mono font-bold"/><Button variant="outline" size="icon" onClick={()=>copy(stats.code||"")}><Copy className="h-4 w-4"/></Button></div></div><div className="space-y-1.5"><Label>General ResKonnect link</Label><div className="flex gap-2"><Input readOnly value={genericLink}/><Button variant="outline" size="icon" onClick={()=>copy(genericLink)}><Copy className="h-4 w-4"/></Button></div></div></CardContent></Card>

      <Card className="border-amber-500/25"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><CardTitle className="flex items-center gap-2"><Building2 className="h-5 w-5 text-primary"/>Choose accommodations to recruit for</CardTitle><CardDescription className="mt-1">Each selected residence gets its own trackable link, so the residence, recruiter, application and placement stay connected.</CardDescription></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search residence or campus…"/></div></div></CardHeader><CardContent>{filtered.length===0?<p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No residences are currently open to the approved recruiter network.</p>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.slice(0,60).map((r)=><div key={r.id} className="overflow-hidden rounded-2xl border bg-background"><div className="relative h-36 bg-muted"><img src={r.studio_image_url||r.cover_image_url||r.image_url||"/placeholder.svg"} alt="" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/><div className="absolute bottom-3 left-3 right-3 text-white"><p className="line-clamp-1 font-black">{r.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-white/80"><MapPin className="h-3 w-3"/>{r.campus||r.city||r.address||"Accommodation"}</p></div></div><div className="space-y-3 p-4"><div className="flex items-center justify-between gap-2"><Badge variant="outline">Quality {r.data_quality_score||0}%</Badge><span className="text-xs font-bold text-primary">R{Number(r.commission_amount||0).toLocaleString("en-ZA")} / placement</span></div>{r.residence_message&&<p className="line-clamp-2 text-xs leading-5 text-muted-foreground">{r.residence_message}</p>}<Button className="w-full" variant={selectedIds.has(r.id)?"outline":"default"} disabled={selecting===r.id} onClick={()=>void choose(r.id)}>{selecting===r.id?"Activating…":selectedIds.has(r.id)?"Refresh & copy link":"Recruit this residence"}</Button></div></div>)}</div>}</CardContent></Card>

      {links.length>0&&<Card><CardHeader><CardTitle>Your residence campaign links</CardTitle><CardDescription>Use these links when you are specifically promoting one accommodation.</CardDescription></CardHeader><CardContent className="space-y-3">{links.map((l)=>{const res=Array.isArray(l.residences)?l.residences[0]:l.residences;const url=`${window.location.origin}/rr/${l.link_key}`;return <div key={l.id} className="flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate font-bold">{res?.name||"Residence campaign"}</p><p className="truncate text-xs text-muted-foreground">{url}</p></div><Button variant="outline" onClick={()=>copy(url)}><Copy className="mr-2 h-4 w-4"/>Copy campaign link</Button></div>;})}</CardContent></Card>}

      <div className="grid gap-4 md:grid-cols-3"><Money label="Pending commission" value={stats.pending_commission}/><Money label="Approved commission" value={stats.approved_commission}/><Money label="Total paid" value={stats.paid_commission}/></div>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Trophy className="h-5 w-5 text-primary"/>Student recruitment bonus</CardTitle><CardDescription>10 verified placements unlock the current platform bonus.</CardDescription></CardHeader><CardContent><div className="mb-2 flex justify-between text-sm font-semibold"><span>{approved} / {bonusTarget} placements</span><span>{Math.round(bonusProgress)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${bonusProgress}%`}}/></div></CardContent></Card>

      <Card><CardHeader><CardTitle>Referred students</CardTitle><CardDescription>Conversion status for students attributed to your recruiter code.</CardDescription></CardHeader><CardContent>{applicants.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No referred applications yet.</p>:<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Residence</TableHead><TableHead>Application</TableHead><TableHead>Referral</TableHead><TableHead className="text-right">Commission</TableHead></TableRow></TableHeader><TableBody>{applicants.map((a)=><TableRow key={a.application_id}><TableCell><p className="font-medium">{a.student_name||"Applicant"}</p><p className="text-xs text-muted-foreground">{a.student_number||"—"}</p></TableCell><TableCell>{a.residence_name||"—"}</TableCell><TableCell><Badge variant="outline">{a.application_status}</Badge></TableCell><TableCell><Badge>{a.referral_status}</Badge></TableCell><TableCell className="text-right font-bold">R{Number(a.commission_amount||0).toFixed(0)}</TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>
    </>}
  </div></DashboardLayout>;
}

function Metric({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <Card><CardContent className="p-4"><Icon className="h-5 w-5 text-primary"/><p className="mt-2 text-2xl font-black">{value??0}</p><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p></CardContent></Card>;}
function Money({label,value}:{label:string;value:any}){return <Card><CardContent className="flex items-center gap-3 p-5"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary"><Wallet className="h-5 w-5"/></div><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-black">R{Number(value||0).toLocaleString("en-ZA")}</p></div></CardContent></Card>;}
