import {useCallback,useEffect,useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {supabase} from '@/integrations/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import DashboardLayout from '@/components/DashboardLayout';
import SEO from '@/components/SEO';
import PartnerIdentityPanel from '@/components/partners/PartnerIdentityPanel';
import PartnerApprovalConsole from '@/components/partners/PartnerApprovalConsole';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
import {publicUrl} from '@/lib/publicUrl';

type Residence={id:string;name:string;address:string|null;campus:string|null;city:string|null;cover_image_url:string|null;image_url:string|null;available_spots:number|null;commission_amount:number|null;residence_message:string|null};
type Scope={scope_kind:string;scope_value:string;state:string};
export default function RecruiterDashboard(){const {user}=useAuth();const navigate=useNavigate();const [stats,setStats]=useState<any>(null);const [applicants,setApplicants]=useState<any[]>([]);const [residences,setResidences]=useState<Residence[]>([]);const [links,setLinks]=useState<any[]>([]);const [profile,setProfile]=useState<any>(null);const [scopes,setScopes]=useState<Scope[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');const [selecting,setSelecting]=useState('');
 const load=useCallback(async()=>{if(!user){setLoading(false);return;}setLoading(true);const [s,a,r,l,p]=await Promise.all([(supabase as any).from('recruiter_dashboard_v').select('*').eq('user_id',user.id).maybeSingle(),(supabase as any).from('recruiter_applicants_v').select('*').eq('referral_agent_user_id',user.id).order('referred_at',{ascending:false}).limit(300),(supabase as any).from('recruitable_residences_v').select('*').order('data_quality_score',{ascending:false}).limit(400),(supabase as any).from('recruiter_residence_links').select('id,link_key,residence_id,is_active,residences(name,slug,campus)').eq('recruiter_user_id',user.id).eq('is_active',true),(supabase as any).from('rk_partner_profiles').select('*').eq('user_id',user.id).eq('kind','residence').maybeSingle()]);setError([s,a,r,l,p].find(x=>x.error)?.error?.message||'');setStats(s.data||null);setApplicants(a.data||[]);setResidences(r.data||[]);setLinks(l.data||[]);setProfile(p.data||null);if(p.data){const result=await(supabase as any).from('rk_partner_scopes').select('scope_kind,scope_value,state').eq('profile_id',p.data.id);setScopes(result.data||[]);}else setScopes([]);setLoading(false);},[user?.id]);useEffect(()=>{void load();},[load]);
 const approvedResidenceIds=new Set(scopes.filter(s=>s.scope_kind==='residence'&&s.state==='approved').map(s=>s.scope_value));const approvedCampuses=new Set(scopes.filter(s=>s.scope_kind==='campus'&&s.state==='approved').map(s=>s.scope_value.toLowerCase()));const chosenIds=new Set(links.map(l=>l.residence_id));const approvedRecruiter=stats?.status==='approved';
 const eligible=useMemo(()=>residences.filter(r=>(!profile||(profile.status==='published'&&approvedResidenceIds.has(r.id)))&&`${r.name} ${r.address||''} ${r.campus||''} ${r.city||''}`.toLowerCase().includes(search.toLowerCase())),[residences,profile,scopes,search]);
 const copy=async(text:string)=>{if(!text)return;try{await navigator.clipboard.writeText(text);toast.success('Link copied');}catch{toast.error('Could not copy link');}};
 const choose=async(r:Residence)=>{if(!approvedRecruiter)return toast.error('Recruiter approval is required');if(profile&&(!approvedResidenceIds.has(r.id)||profile.status!=='published'))return toast.error('Residence Admin must approve this residence for your active profile');setSelecting(r.id);const {data,error}=await(supabase as any).rpc('recruiter_select_residence',{p_residence_id:r.id});setSelecting('');if(error)return toast.error(error.message);toast.success(`${r.name} campaign activated`);await copy(publicUrl('/rr/'+data.linkKey));await load();};
 return <DashboardLayout><SEO noIndex title="Residence Recruiter Workspace | ResKonnect" description="Manage approved accommodation campaigns, leads, placements and recruitment commissions."/><main className="mx-auto max-w-7xl space-y-6 px-4 py-8 pb-24 sm:px-6"><section className="rounded-3xl bg-[#071326] p-7 text-white"><Badge className="bg-[#F5B32F] text-[#071326]">RESKONNECT · LIVING</Badge><h1 className="mt-3 text-3xl font-black">Residence Recruitment Command Centre</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-white/70">Recruit students for residences assigned to you. Each property has a dedicated attribution link; leads, applications, confirmed placements and approved commissions are tracked separately. Students may stay for both semesters without becoming two placements.</p></section>
 {loading?<p className="py-10 text-center">Loading recruiter workspace…</p>:<>{error&&<p role="alert" className="rounded-xl border border-destructive p-4">{error}<Button className="ml-2" variant="outline" onClick={()=>void load()}>Retry</Button></p>}
 {!approvedRecruiter?<Card><CardContent className="space-y-3 p-6"><h2 className="text-xl font-bold">Recruiter approval required</h2><p className="text-sm text-muted-foreground">Your residence campaigns will become available after ResKonnect reviews and approves your recruiter application.</p><Button onClick={()=>navigate('/recruit')}>Apply / check recruitment status</Button></CardContent></Card>:<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Referral visits',stats.total_clicks],['Student registrations',stats.total_signups],['Accommodation applications',stats.total_applications],['Approved placements',stats.approved_count]].map(([name,value])=><Card key={String(name)}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{name}</p><p className="mt-2 text-3xl font-black">{Number(value||0).toLocaleString('en-ZA')}</p></CardContent></Card>)}</div>
 <PartnerIdentityPanel kind="residence" legacySlug={stats.code?`res-${String(stats.code).toLowerCase().replace(/[^a-z0-9-]/g,'')}`:undefined} legacyName="Residence recruiter"/>
 <Card><CardHeader><CardTitle>General recruitment link</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Input className="min-w-[200px] flex-1" readOnly value={stats.code?publicUrl('/r/'+stats.code):''}/><Button variant="outline" onClick={()=>void copy(stats.code?publicUrl('/r/'+stats.code):'')}>Copy</Button>{profile?.status==='published'&&<Button asChild variant="outline"><Link to={'/partners/'+profile.slug}>View public profile</Link></Button>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Approved accommodation campaigns</CardTitle><p className="text-sm text-muted-foreground">A Residence Admin approves the exact residences you may recruit for. An approved campus assignment defines your territory; it does not automatically authorise every property in that campus. Published availability must be confirmed before promising a room.</p></CardHeader><CardContent className="space-y-4"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search approved accommodation or campus" aria-label="Search approved residences"/>{profile?.status!=='published'&&<p className="rounded-xl bg-amber-500/10 p-3 text-sm">Complete your profile and wait for publication and residence assignments. Existing legacy campaigns remain visible below.</p>}{profile?.status==='published'&&approvedCampuses.size>0&&<p className="text-sm text-muted-foreground">Approved territory: {[...approvedCampuses].join(', ')}</p>}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{eligible.map(r=><article key={r.id} className="overflow-hidden rounded-2xl border"><div className="h-36 bg-muted">{(r.cover_image_url||r.image_url)&&<img loading="lazy" className="h-full w-full object-cover" alt={r.name} src={r.cover_image_url||r.image_url||''}/>}</div><div className="space-y-2 p-4"><h3 className="font-bold">{r.name}</h3><p className="text-sm text-muted-foreground">{r.campus||r.city||r.address||'Area not set'} · {Number(r.available_spots||0)} published spaces</p><p className="text-sm">Approved programme commission: R{Number(r.commission_amount||0).toLocaleString('en-ZA')} per eligible verified placement</p>{r.residence_message&&<p className="text-xs text-muted-foreground">{r.residence_message}</p>}<Button className="w-full" disabled={Boolean(selecting)||Number(r.available_spots||0)<=0} onClick={()=>void choose(r)}>{selecting===r.id?'Activating…':chosenIds.has(r.id)?'Refresh / copy campaign link':'Activate assigned campaign'}</Button></div></article>)}</div>{!eligible.length&&<p className="rounded-xl border border-dashed p-6 text-sm text-muted-foreground">No approved recruitable residences match your search. Request an assignment in your public-profile panel or contact the Residence Admin.</p>}</CardContent></Card>
 {links.length>0&&<Card><CardHeader><CardTitle>Existing residence referral links</CardTitle></CardHeader><CardContent className="space-y-2">{links.map(l=><div key={l.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><span className="font-semibold">{l.residences?.name||'Residence campaign'}</span><Button variant="outline" onClick={()=>void copy(publicUrl('/rr/'+l.link_key))}>Copy trackable link</Button></div>)}</CardContent></Card>}
 <div className="grid gap-3 md:grid-cols-3">{[['Pending commission',stats.pending_commission],['Approved commission',stats.approved_commission],['Paid commission',stats.paid_commission]].map(([label,value])=><Card key={String(label)}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-black">R{Number(value||0).toLocaleString('en-ZA')}</p></CardContent></Card>)}</div>
 <Card><CardHeader><CardTitle>Attributed student applications</CardTitle></CardHeader><CardContent><div className="space-y-2">{applicants.map(a=><div key={a.application_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-semibold">{a.student_name||'Applicant'}</p><p className="text-sm text-muted-foreground">{a.residence_name||'Residence pending'} · {a.application_status}</p></div><div><Badge variant="outline">{a.referral_status}</Badge><p className="mt-1 text-xs">R{Number(a.commission_amount||0).toFixed(0)} eligible amount</p></div></div>)}{!applicants.length&&<p className="text-sm text-muted-foreground">No attributed accommodation applications yet.</p>}</div></CardContent></Card>
 </>}
 </>}
 <PartnerApprovalConsole kind="residence"/>
 </main></DashboardLayout>;
}
