import { useCallback, useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { BedDouble, CheckCircle2, Plus, RefreshCw, Save, ShieldCheck, Trash2 } from "lucide-react";
import SEO from "@/components/SEO";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type { ResidencePortalContext } from "./ResidenceLayout";

const emptyRoom={name:"",academic_year:2027,capacity:0,available_beds:0,private_price:"",nsfas_price:"",deposit:"",admin_fee:"",reservation_fee:"",promo_price:""};
const money=(value:any)=>value===null||value===undefined||value===""?"—":`R${Number(value).toLocaleString("en-ZA")}`;

export default function ResidenceInventory(){
  const {residence}=useOutletContext<ResidencePortalContext>();
  const [rooms,setRooms]=useState<any[]>([]);
  const [draft,setDraft]=useState<any>(emptyRoom);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState<string|null>(null);

  const load=useCallback(async()=>{if(!residence?.id)return;setLoading(true);const {data,error}=await (supabase as any).from("residence_room_types").select("*").eq("residence_id",residence.id).order("academic_year",{ascending:false}).order("name");if(error)toast.error(error.message||"Could not load inventory");else setRooms(data||[]);setLoading(false);},[residence?.id]);
  useEffect(()=>{void load();},[load]);
  const active=useMemo(()=>rooms.filter((r)=>r.is_active!==false),[rooms]);
  const totals=useMemo(()=>({capacity:active.reduce((n,r)=>n+Number(r.capacity||0),0),available:active.reduce((n,r)=>n+Number(r.available_beds||0),0),verified:active.filter((r)=>Boolean(r.price_verified_at)).length,confirmed:active.filter((r)=>Boolean(r.landlord_confirmed_at)).length}),[active]);
  const numeric=(value:any)=>value===""||value===null||value===undefined?null:Number(value);

  const createRoom=async()=>{if(!residence?.id||!draft.name.trim())return toast.error("Enter a room type name");setSaving("new");const {error}=await (supabase as any).from("residence_room_types").insert({residence_id:residence.id,name:draft.name.trim(),academic_year:Number(draft.academic_year||2027),capacity:Number(draft.capacity||0),available_beds:Number(draft.available_beds||0),private_price:numeric(draft.private_price),nsfas_price:numeric(draft.nsfas_price),deposit:numeric(draft.deposit),admin_fee:numeric(draft.admin_fee),reservation_fee:numeric(draft.reservation_fee),promo_price:numeric(draft.promo_price),is_active:true});setSaving(null);if(error)return toast.error(error.message||"Could not add room type");setDraft(emptyRoom);toast.success("Room type added");void load();};
  const updateRoom=async(room:any,patch:Record<string,any>)=>{setSaving(room.id);const {error}=await (supabase as any).from("residence_room_types").update(patch).eq("id",room.id);setSaving(null);if(error)return toast.error(error.message||"Could not save pricing");toast.success("Room data saved and landlord-confirmed");void load();};
  const removeRoom=async(room:any)=>{const {error}=await (supabase as any).from("residence_room_types").update({is_active:false}).eq("id",room.id);if(error)return toast.error(error.message);toast.success("Room type archived");void load();};
  if(!residence)return <div className="py-16 text-center text-sm text-muted-foreground">Loading residence inventory…</div>;

  return <><SEO noIndex title={`Inventory & Pricing | ${residence.name} | ResKonnect`} description={`Room inventory and verified pricing for ${residence.name}.`}/><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-primary">Landlord Portal · Inventory OS</p><h1 className="mt-1 text-3xl font-black">Room inventory & pricing</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Manage real room availability, private rates, NSFAS-context rates, deposits and fees. Residence updates are landlord-confirmed; ResKonnect verification is a separate platform control.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</Button></div>
    <Card className="border-primary/20 bg-primary/[0.025]"><CardContent className="flex items-start gap-3 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 text-primary"/><div><p className="text-sm font-bold">Verification separation</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Changing a price automatically removes any previous verified-price stamp until ResKonnect reviews the new rate. Residence portal users cannot self-verify pricing.</p></div></CardContent></Card>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Configured capacity" value={totals.capacity}/><Metric label="Available beds" value={totals.available}/><Metric label="Landlord confirmed" value={`${totals.confirmed}/${active.length}`}/><Metric label="Platform verified" value={`${totals.verified}/${active.length}`}/></div>

    <Card className="border-primary/20"><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5 text-primary"/>Add a room type</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Room type","name","Single / Sharing / Bachelor","text"],["Academic year","academic_year","2027","number"],["Capacity","capacity","0","number"],["Available beds","available_beds","0","number"],["Private monthly rate","private_price","e.g. 3000","number"],["NSFAS-context rate","nsfas_price","Funded rate","number"],["Deposit","deposit","Optional","number"],["Admin fee","admin_fee","Optional","number"],["Reservation fee","reservation_fee","Optional","number"],["Promo price","promo_price","Optional","number"]].map(([label,key,placeholder,type])=><div key={key} className="space-y-1.5"><Label>{label}</Label><Input type={type} value={draft[key]} placeholder={placeholder} onChange={(e)=>setDraft((d:any)=>({...d,[key]:e.target.value}))}/></div>)}<div className="flex items-end sm:col-span-2 lg:col-span-5"><Button className="w-full" onClick={()=>void createRoom()} disabled={saving==="new"}><Plus className="mr-2 h-4 w-4"/>Add room type</Button></div></CardContent></Card>

    {loading?<Card><CardContent className="py-16 text-center text-sm text-muted-foreground">Loading room inventory…</CardContent></Card>:active.length===0?<Card><CardContent className="py-16 text-center"><BedDouble className="mx-auto h-9 w-9 text-muted-foreground"/><p className="mt-3 font-bold">No room-level inventory configured yet</p><p className="mt-1 text-sm text-muted-foreground">Add your real room types above. ResKonnect will never invent a rate on your behalf.</p></CardContent></Card>:<div className="space-y-4">{active.map((room)=><Card key={room.id}><CardContent className="p-4 sm:p-5"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">{room.name}</h2><Badge variant="outline">{room.academic_year}</Badge>{room.price_verified_at?<Badge className="gap-1"><CheckCircle2 className="h-3 w-3"/>Platform verified</Badge>:room.landlord_confirmed_at?<Badge variant="secondary">Landlord confirmed</Badge>:<Badge variant="outline">Confirmation needed</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">Private {money(room.private_price)} · NSFAS {money(room.nsfas_price)} · {room.available_beds}/{room.capacity} beds available</p></div><Button size="sm" variant="ghost" className="self-start text-destructive" onClick={()=>void removeRoom(room)}><Trash2 className="h-4 w-4"/></Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Capacity","capacity"],["Available","available_beds"],["Private rate","private_price"],["NSFAS rate","nsfas_price"],["Promo price","promo_price"],["Deposit","deposit"],["Admin fee","admin_fee"],["Reservation fee","reservation_fee"]].map(([label,key])=><div key={key} className="space-y-1.5"><Label className="text-xs">{label}</Label><Input type="number" defaultValue={room[key]??""} onBlur={(e)=>{const val=e.target.value===""?null:Number(e.target.value);if(val!==room[key])void updateRoom(room,{[key]:val});}}/></div>)}</div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><Save className="h-3.5 w-3.5"/><span>Fields save when you leave them. Each price change records the residence confirmation timestamp.</span></div></CardContent></Card>)}</div>}
  </div></>;
}
function Metric({label,value}:{label:string;value:number|string}){return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></CardContent></Card>;}
