import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

type Kind='application'|'residence';
type Profile={id:string;slug:string;display_name:string;bio:string;campus:string;tiktok_url:string|null;status:string;bio_review:string;bio_verified_until:string|null};
type Scope={id:string;scope_kind:string;scope_value:string;state:string};
export default function PartnerIdentityPanel({kind,legacySlug,legacyName}:{kind:Kind;legacySlug?:string;legacyName?:string}) {
 const {user}=useAuth();const [profile,setProfile]=useState<Profile|null>(null);const [scopes,setScopes]=useState<Scope[]>([]);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 const [name,setName]=useState('');const [slug,setSlug]=useState('');const [bio,setBio]=useState('');const [campus,setCampus]=useState('');const [tiktok,setTiktok]=useState('');const [scope,setScope]=useState('');const [scopeKind,setScopeKind]=useState(kind==='application'?'institution':'campus');
 const load=useCallback(async()=>{if(!user){setLoading(false);return;}setLoading(true);const {data,error}=await (supabase as any).from('rk_partner_profiles').select('*').eq('user_id',user.id).eq('kind',kind).maybeSingle();if(error)toast.error(error.message);const p=data as Profile|null;setProfile(p);if(p){setName(p.display_name);setSlug(p.slug);setBio(p.bio);setCampus(p.campus);setTiktok(p.tiktok_url||'');const r=await(supabase as any).from('rk_partner_scopes').select('id,scope_kind,scope_value,state').eq('profile_id',p.id).order('scope_kind');if(r.error)toast.error(r.error.message);setScopes(r.data||[]);}else{setName(legacyName||'');setSlug(legacySlug||'');setScopes([]);}setLoading(false);},[user?.id,kind,legacyName,legacySlug]);
 useEffect(()=>{void load();},[load]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!user)return;setBusy(true);const {error}=await(supabase as any).rpc('rk_save_partner_profile',{p_kind:kind,p_slug:slug.trim().toLowerCase(),p_name:name.trim(),p_bio:bio.trim(),p_campus:campus.trim(),p_tiktok_url:tiktok.trim()||null});setBusy(false);if(error)return toast.error(error.message);toast.success('Profile saved. Publication and link verification require ResKonnect approval.');await load();};
 const request=async(e:React.FormEvent)=>{e.preventDefault();if(!profile)return;setBusy(true);const {error}=await(supabase as any).rpc('rk_request_partner_scope',{p_profile_id:profile.id,p_kind:scopeKind,p_value:scope.trim()});setBusy(false);if(error)return toast.error(error.message);setScope('');toast.success('Assignment submitted for admin approval.');await load();};
 const profileUrl=profile?`${window.location.origin}/partners/${profile.slug}`:'';
 const verified=Boolean(profile?.status==='published'&&profile?.bio_review==='verified'&&profile.bio_verified_until&&Date.parse(profile.bio_verified_until)>Date.now());
 if(!user)return null;
 return <Card className="border-primary/20"><CardHeader><CardTitle>My public {kind==='application'?'application-assistance':'residence recruitment'} profile</CardTitle><p className="text-sm text-muted-foreground">Students can discover you without arriving from TikTok. Your public page and approved work assignments are separate from private student-case permissions.</p></CardHeader><CardContent className="space-y-5">{loading?<p>Loading profile…</p>:<>
 <div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{profile?.status||'Not created'}</Badge><Badge variant={verified?'default':'secondary'}>{verified?'Verified TikTok bio':profile?.bio_review==='pending'?'Bio review pending':'Bio link not verified'}</Badge>{verified&&<Badge>Verified directory visibility and aggregate analytics</Badge>}</div>
 <form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Public display name<Input required maxLength={120} minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm font-semibold">Public profile handle<Input required pattern="[a-z0-9][a-z0-9-]{2,79}" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))} placeholder="e.g. tumelo-applications"/></label><label className="text-sm font-semibold">Campus / area<Input maxLength={150} value={campus} onChange={e=>setCampus(e.target.value)} placeholder="Pretoria West"/></label><label className="text-sm font-semibold">Your TikTok profile URL<Input type="url" maxLength={250} value={tiktok} onChange={e=>setTiktok(e.target.value)} placeholder="https://www.tiktok.com/@yourhandle"/></label><label className="text-sm font-semibold sm:col-span-2">How you assist students<Textarea maxLength={2500} value={bio} onChange={e=>setBio(e.target.value)}/></label><Button disabled={busy} className="sm:col-span-2">{busy?'Saving…':'Save public profile'}</Button></form>
 {profile&&<div className="rounded-xl border bg-muted/30 p-4 text-sm"><p className="font-bold">Your permanent ResKonnect profile link</p><p className="mt-1 break-all font-mono text-xs">{profileUrl}</p><p className="mt-2 text-muted-foreground">Place this exact link in your TikTok bio. ResKonnect must check your live TikTok profile before activating the badge; a submitted URL alone does not qualify. Verification expires and can be revoked. Your public profile never grants access to student documents.</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={()=>{void navigator.clipboard.writeText(profileUrl).then(()=>toast.success('Profile link copied')).catch(()=>toast.error('Copy failed'));}}>Copy profile link</Button><Button type="button" variant="outline" onClick={async()=>{const {error}=await(supabase as any).rpc('rk_request_bio_review',{p_profile_id:profile.id});if(error)toast.error(error.message);else{toast.success('Verification requested');await load();}}}>Request bio verification</Button><Button asChild variant="outline"><Link to={`/partners/${profile.slug}`}>View public profile</Link></Button></div></div>}
 {profile&&<div className="space-y-3"><h3 className="font-bold">{kind==='application'?'Institutions you assist with':'Your recruitment territory and residences'}</h3><p className="text-sm text-muted-foreground">Select your preferred {kind==='application'?'universities and TVET colleges':'campus and residence assignments'}. An administrator must approve each assignment before you can work under that scope.</p><form onSubmit={request} className="flex flex-wrap gap-2"><select className="rounded-md border bg-background p-2 text-sm" aria-label="Assignment type" value={scopeKind} onChange={e=>{setScopeKind(e.target.value);setScope('');}}>{kind==='application'?<option value="institution">University / TVET college</option>:<><option value="campus">Campus / territory</option><option value="residence">Residence ID</option></>}</select><Input required className="min-w-[180px] flex-1" value={scope} onChange={e=>setScope(e.target.value)} placeholder={scopeKind==='residence'?'Select an assigned residence from the list below':scopeKind==='campus'?'Campus name':'Institution name'}/><Button disabled={busy}>Request approval</Button></form><div className="flex flex-wrap gap-2">{scopes.map(s=><Badge variant={s.state==='approved'?'default':'outline'} key={s.id}>{s.scope_value} · {s.state}</Badge>)}{!scopes.length&&<p className="text-sm text-muted-foreground">No assignments requested yet.</p>}</div></div>}
 </>}</CardContent></Card>;
}
