import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import SEO from "@/components/SEO";
import { supabase } from "@/integrations/supabase/client";
import { SITE_URL } from "@/lib/seo/seoConfig";

export default function PublicOpportunityDetail(){
  const {slug}=useParams(); const [item,setItem]=useState<any>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{const {data}=await supabase.from("public_opportunities" as any).select("*").eq("slug",slug).eq("is_published",true).maybeSingle();setItem(data);setLoading(false)})()},[slug]);
  if(loading)return <main className="min-h-screen bg-background"/>;
  if(!item)return <main className="mx-auto max-w-4xl px-4 py-20"><SEO title="Opportunity not found | ResKonnect" description="This opportunity is not currently published." noIndex/><h1 className="text-3xl font-bold">Opportunity not available</h1><Link to="/opportunities" className="mt-6 inline-block text-primary">Browse opportunities</Link></main>;
  const title=`${item.title} | ResKonnect Opportunities`;
  const description=(item.description||`View ${item.opportunity_type} details, requirements, closing date and official application information.`).slice(0,155);
  const isJob=["internship","job","graduate","learnership","wil"].some((x)=>String(item.opportunity_type).toLowerCase().includes(x));
  const schema=isJob?{"@context":"https://schema.org","@type":"JobPosting",title:item.title,description:item.description||description,datePosted:item.date_posted,validThrough:item.closing_date,employmentType:item.employment_type,hiringOrganization:item.organisation?{"@type":"Organization",name:item.organisation}:undefined,jobLocation:item.location?{"@type":"Place",address:{"@type":"PostalAddress",addressLocality:item.location,addressRegion:item.province,addressCountry:"ZA"}}:undefined,url:`${SITE_URL}/opportunities/${item.slug}`}:{"@context":"https://schema.org","@type":"WebPage",name:item.title,description,url:`${SITE_URL}/opportunities/${item.slug}`};
  return <main className="min-h-screen bg-background text-foreground"><SEO title={title} description={description} canonicalPath={`/opportunities/${item.slug}`} jsonLd={schema}/><div className="mx-auto max-w-5xl px-4 py-12 md:py-20"><Link to="/opportunities" className="text-sm font-semibold text-primary">← Opportunities</Link><p className="mt-10 text-xs font-bold uppercase tracking-[0.2em] text-primary">{item.opportunity_type}</p><h1 className="mt-3 text-4xl font-black tracking-tight md:text-6xl">{item.title}</h1><p className="mt-4 text-lg text-muted-foreground">{[item.organisation,item.location,item.province].filter(Boolean).join(" • ")}</p><div className="mt-10 grid gap-8 lg:grid-cols-[1.5fr_1fr]"><article className="space-y-8"><section><h2 className="text-2xl font-bold">Opportunity overview</h2><p className="mt-3 whitespace-pre-line leading-7 text-muted-foreground">{item.description||description}</p></section>{item.requirements&&<section><h2 className="text-2xl font-bold">Requirements</h2><p className="mt-3 whitespace-pre-line leading-7 text-muted-foreground">{item.requirements}</p></section>}</article><aside className="rounded-2xl border border-border bg-card p-6"><h2 className="font-bold">Key dates</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="text-muted-foreground">Posted</dt><dd className="font-semibold">{new Date(item.date_posted).toLocaleDateString("en-ZA")}</dd></div><div><dt className="text-muted-foreground">Closing date</dt><dd className="font-semibold">{item.closing_date?new Date(item.closing_date).toLocaleDateString("en-ZA"):"Check official source"}</dd></div><div><dt className="text-muted-foreground">Last verified</dt><dd className="font-semibold">{item.last_verified_at?new Date(item.last_verified_at).toLocaleDateString("en-ZA"):"Verification required"}</dd></div></dl>{item.application_url&&<a className="mt-6 inline-flex rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground" href={item.application_url} rel="nofollow noopener noreferrer" target="_blank">Apply at official source</a>}</aside></div></div></main>;
}
