import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.79.0";

const env=(n:string)=>Deno.env.get(n)||"";
const supabaseUrl=env("SUPABASE_URL")||env("EXTERNAL_SUPABASE_URL");
const serviceKey=env("SUPABASE_SERVICE_ROLE_KEY")||env("EXTERNAL_SUPABASE_SERVICE_ROLE_KEY");
const accountSid=env("TWILIO_ACCOUNT_SID");
const authToken=env("TWILIO_AUTH_TOKEN");
const fromNumber=env("TWILIO_WHATSAPP_FROM");
const statusCallback=env("TWILIO_WHATSAPP_STATUS_CALLBACK_URL");
const PUBLIC_BASE="https://www.reskonnect.org";
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const digits=(v="")=>String(v).replace(/^whatsapp:/i,"").replace(/\D/g,"");
const e164=(v="")=>{let d=digits(v);if(d.startsWith("0")&&d.length===10)d=`27${d.slice(1)}`;if(!d.startsWith("27")&&d.length===9)d=`27${d}`;return d?`+${d}`:"";};
const wa=(v="")=>{const n=e164(v);return n?`whatsapp:${n}`:"";};
const basic=()=>`Basic ${btoa(`${accountSid}:${authToken}`)}`;
const firstName=(v="")=>String(v||"there").trim().split(/\s+/)[0]||"there";
const canonical=(url="")=>{const v=String(url||"").trim();if(!v)return PUBLIC_BASE;return v.replace(/^https:\/\/reskonnect\.org/i,PUBLIC_BASE);};

async function authorized(req:Request,service:any){const token=req.headers.get("x-adminos-cron-token")||"";if(!token)return false;const row=await service.from("adminos_scheduler_secrets").select("secret_value").eq("secret_key","whatsapp_event_worker").maybeSingle();const expected=String(row.data?.secret_value||"");if(!expected||token.length!==expected.length)return false;let diff=0;for(let i=0;i<token.length;i++)diff|=token.charCodeAt(i)^expected.charCodeAt(i);return diff===0;}
async function twilioSend(form:URLSearchParams){if(!accountSid||!authToken||!fromNumber)throw new Error("Twilio WhatsApp is not configured");if(statusCallback)form.set("StatusCallback",statusCallback);const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`,{method:"POST",headers:{Authorization:basic(),"Content-Type":"application/x-www-form-urlencoded"},body:form});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||`Twilio HTTP ${r.status}`);return d;}
async function permission(service:any,contactId:string|null){if(!contactId)return{allowed:true,reason:"no_contact"};const row=await service.from("adminos_communication_preferences").select("do_not_contact,whatsapp_allowed").eq("contact_id",contactId).maybeSingle();if(row.data?.do_not_contact)return{allowed:false,reason:"do_not_contact"};if(row.data?.whatsapp_allowed===false)return{allowed:false,reason:"whatsapp_disabled"};return{allowed:true,reason:"allowed"};}
async function resolveContext(service:any,event:any){let phone=e164(event.phone||"");let profile:any=null;if(event.user_id){const p=await service.from("profiles").select("id,full_name,phone,phone_number,email").eq("id",event.user_id).maybeSingle();profile=p.data||null;phone=phone||e164(profile?.phone||profile?.phone_number||"");}if(!phone)throw new Error("No WhatsApp phone number is available");let contactId=event.contact_id||null;if(!contactId){const resolved=await service.rpc("adminos_resolve_contact",{p_full_name:event.payload?.user_name||profile?.full_name||null,p_email:profile?.email||null,p_phone:phone,p_profile_user_id:event.user_id||null,p_source_type:"site_event",p_source_id:event.source_id||null,p_metadata:{event_type:event.event_type,source_table:event.source_table}});contactId=resolved.data||null;if(contactId)await service.from("adminos_whatsapp_site_events").update({contact_id:contactId,phone}).eq("id",event.id);}const norm=digits(phone);let thread=(await service.from("adminos_whatsapp_threads").select("*").eq("normalized_address",norm).maybeSingle()).data;if(!thread){const created=await service.from("adminos_whatsapp_threads").insert({contact_id:contactId,channel_address:wa(phone),normalized_address:norm,status:"open",mode:"ai_auto",metadata:{source:"site_event"}}).select("*").single();if(created.error)throw created.error;thread=created.data;}else if(contactId&&!thread.contact_id){await service.from("adminos_whatsapp_threads").update({contact_id:contactId}).eq("id",thread.id);thread.contact_id=contactId;}return{phone,profile,contactId,thread};}
function contentFor(event:any){if(String(event.event_type||"").startsWith("proactive_"))return"rk_next_step_reminder_v2";switch(event.event_type){case"application_created":return"rk_application_confirmation";case"reservation_created":case"residence_enquiry_created":return"rk_reservation_confirmation";case"document_attention":return"rk_missing_documents";case"wil_application_created":return"rk_wil_confirmation";case"support_query_created":return"rk_support_confirmation";case"application_status_changed":case"reservation_status_changed":case"wil_status_changed":return"rk_status_update_v2";case"csat_request":return"rk_csat_request";case"service_recovery_ack":case"service_recovery":return"rk_service_recovery";default:return null;}}
function variableMap(event:any,key:string){const p=event.payload||{};const name=firstName(p.user_name||p.full_name||"there");if(key==="rk_application_confirmation")return{"1":name,"2":String(p.residence_name||"your selected residence")};if(key==="rk_reservation_confirmation")return{"1":name,"2":String(p.residence_name||"your selected accommodation")};if(key==="rk_status_update_v2"){const subject=event.event_type.startsWith("reservation")?"reservation":event.event_type.startsWith("wil")?"WIL application":"application";return{"1":name,"2":subject,"3":String(p.status||"updated")};}if(key==="rk_next_step_reminder_v2")return{"1":name,"2":String(p.next_step||p.title||p.action_title||"Review your ResKonnect next step"),"3":canonical(p.action_url||p.url||PUBLIC_BASE)};return{"1":name};}
async function richRow(service:any,key:string){const r=await service.from("adminos_whatsapp_rich_content").select("*").eq("content_key",key).maybeSingle();return r.data||null;}
async function persistOutbound(service:any,ctx:any,sent:any,event:any,bodyText:string|null,metadata:any,media:any[]=[]){const now=new Date().toISOString();const row=await service.from("adminos_whatsapp_messages").upsert({thread_id:ctx.thread.id,contact_id:ctx.contactId,twilio_message_sid:sent.sid,direction:"outbound",from_address:wa(fromNumber),to_address:wa(ctx.phone),body_text:bodyText,media,message_kind:"transactional",status:sent.status==="queued"?"queued":"sent",risk_level:"green",sent_at:now,metadata:{source:"site_event_worker",author_type:"system",persona:"Dimpho",site_event_id:event.id,event_type:event.event_type,...metadata}},{onConflict:"twilio_message_sid"}).select("id").maybeSingle();await service.from("adminos_whatsapp_threads").update({last_message_at:now,last_outbound_at:now,status:"waiting",updated_at:now}).eq("id",ctx.thread.id);await service.from("adminos_whatsapp_activity").insert({thread_id:ctx.thread.id,actor_id:null,event_type:"site_event.sent",metadata:{site_event_id:event.id,event_type:event.event_type,message_id:row.data?.id||null,twilio_message_sid:sent.sid,...metadata}});}
async function sendRich(service:any,ctx:any,event:any,key:string){const row=await richRow(service,key);if(!row?.content_sid)throw new Error(`Rich content ${key} is not ready`);const windowOpen=Boolean(ctx.thread.customer_window_expires_at&&new Date(ctx.thread.customer_window_expires_at).getTime()>Date.now());if(!windowOpen&&row.approval_required&&row.status!=="approved")return{waiting:true,reason:"template_pending_approval"};const vars=variableMap(event,key);const form=new URLSearchParams({From:wa(fromNumber),To:wa(ctx.phone),ContentSid:row.content_sid});if(Object.keys(vars).length)form.set("ContentVariables",JSON.stringify(vars));const sent=await twilioSend(form);await persistOutbound(service,ctx,sent,event,String(row.config?.body||row.display_name),{content_key:key,content_sid:row.content_sid,variables:vars});return{waiting:false,sent};}
async function sendResidenceMedia(service:any,ctx:any,event:any){const p=event.payload||{};const image=String(p.residence_image||"").trim();if(!image)return;const windowOpen=Boolean(ctx.thread.customer_window_expires_at&&new Date(ctx.thread.customer_window_expires_at).getTime()>Date.now());if(!windowOpen)return;const destination=p.residence_slug?`${PUBLIC_BASE}/find-my-res/${encodeURIComponent(p.residence_slug)}`:`${PUBLIC_BASE}/findmyres`;const body=[p.residence_name?`🏠 ${p.residence_name}`:null,p.academic_year?`Academic year: ${p.academic_year}`:null,p.funding_type?`Funding: ${p.funding_type}`:null,`View & continue: ${destination}`].filter(Boolean).join("\n");const form=new URLSearchParams({From:wa(fromNumber),To:wa(ctx.phone),Body:body,MediaUrl:image});const sent=await twilioSend(form);await persistOutbound(service,ctx,sent,event,body,{rich_media:true,residence_id:p.residence_id||null},[{url:image,content_type:"image/*",source:"residence"}]);}
async function processEvent(service:any,event:any){if(event.event_type==="document_uploaded")return{status:"sent",note:"upload_recorded_no_message"};const ctx=await resolveContext(service,event);const allowed=await permission(service,ctx.contactId);if(!allowed.allowed)return{status:"blocked",reason:allowed.reason};const key=contentFor(event);if(!key)return{status:"sent",note:"no_customer_message_required"};const result=await sendRich(service,ctx,event,key);if(result.waiting)return{status:"waiting_template",reason:result.reason};if(["application_created","reservation_created","residence_enquiry_created"].includes(event.event_type))await sendResidenceMedia(service,ctx,event);return{status:"sent",content_key:key};}
serve(async(req)=>{if(req.method!=="POST")return json({error:"Method not allowed"},405);if(!supabaseUrl||!serviceKey)return json({error:"Supabase runtime is not configured"},500);const service=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false}});if(!(await authorized(req,service)))return json({error:"Unauthorized"},401);const body=await req.json().catch(()=>({}));if(String(body.action||"tick")!=="tick")return json({error:"Unsupported action"},400);const max=Math.max(1,Math.min(100,Number(body.max||30)));const due=await service.from("adminos_whatsapp_site_events").select("*").in("status",["pending","waiting_template","failed"]).lte("available_at",new Date().toISOString()).order("created_at",{ascending:true}).limit(max);const results:any[]=[];for(const event of due.data||[]){await service.from("adminos_whatsapp_site_events").update({status:"processing",attempts:Number(event.attempts||0)+1,updated_at:new Date().toISOString()}).eq("id",event.id);try{const r=await processEvent(service,event);const retry=r.status==="waiting_template"?new Date(Date.now()+15*60*1000).toISOString():event.available_at;await service.from("adminos_whatsapp_site_events").update({status:r.status,available_at:retry,processed_at:r.status==="sent"||r.status==="blocked"?new Date().toISOString():null,last_error:r.reason||null,updated_at:new Date().toISOString()}).eq("id",event.id);results.push({id:event.id,event_type:event.event_type,...r});}catch(e){const err=e instanceof Error?e.message:String(e);const attempts=Number(event.attempts||0)+1;const retry=new Date(Date.now()+Math.min(60,Math.max(5,attempts*5))*60*1000).toISOString();await service.from("adminos_whatsapp_site_events").update({status:attempts>=6?"blocked":"failed",available_at:retry,last_error:err,updated_at:new Date().toISOString()}).eq("id",event.id);results.push({id:event.id,event_type:event.event_type,status:"failed",error:err});}}return json({ok:true,processed:results.length,results});});