-- DEPRECATED: DO NOT RUN THIS FILE AS AN EXPORT VALIDATOR.
--
-- Handover data integrity is now enforced by the versioned GOD MODE OS migrations:
--   20260828070716_handover_god_mode_foundation.sql
--   20260828070751_handover_god_mode_integrity_engine.sql
--   20260828070828_handover_god_mode_workflows.sql
--   20260828070845_handover_god_mode_quarantine_existing_duplicates.sql
--   20260828070946_handover_god_mode_admin_repairs.sql
--   20260828071218_handover_safe_auto_repair_trigger_compat.sql
--   20260828071731_handover_god_mode_status_compat.sql
--
-- Runtime entry points:
--   public.handover_integrity_scan(residence_id, mode)
--   public.handover_safe_auto_repair(residence_id)
--   public.handover_get_record(application_id)
--   public.handover_update_record(application_id, patch)
--   public.handover_bulk_set_funding(application_ids, funding_type)
--   public.prepare_handover_export(residence_id, mode)
--   download-handover-pack Edge Function
--
-- Important safeguards in GOD MODE OS:
--   * no validation bypass path
--   * validation and export rows use one atomic database snapshot
--   * SHA-256 dataset fingerprint and integrity-run receipt
--   * future same-user/same-residence duplicates are blocked in PostgreSQL
--   * existing duplicate extras are quarantined, never silently deleted
--   * approved/conditionally-approved applications require critical handover fields
--   * student number OR 13-digit SA ID is accepted for TVET/matric/private applicants
--   * funding is never guessed; it must be explicitly captured or verified by an authorized operator
--   * source corrections are audit logged
--   * document completeness can be promoted to a blocking requirement with document_handover mode
--
-- The former implementation incorrectly reported jsonb_array_length(errors) as
-- "duplicates_found", causing every validation error to inflate the duplicate metric.
-- That legacy implementation has intentionally been removed to prevent accidental rollback.
