-- Migration: Add Pretoria Main Campus Residences
-- Created on 2025-11-04

create table if not exists residences (
    id bigint generated by default as identity primary key,
    name text not null,
    campus text not null,
    address text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

insert into residences (name, campus, address) values
('Urban Edge Residence', 'Pretoria West (Main Campus)', 'Corner Francis Baard & Beatrix Street, Arcadia'),
('Kingsway Place', 'Pretoria West (Main Campus)', '123 Justice Mahomed Street, Sunnyside'),
('TUT Village', 'Pretoria West (Main Campus)', 'Cnr Park & Steve Biko Road, Arcadia'),
('Student Heights', 'Pretoria West (Main Campus)', '80 Steve Biko Road, Arcadia'),
('Arcadia Living', 'Pretoria West (Main Campus)', '45 Hamilton Street, Arcadia'),
('Campus Edge', 'Pretoria West (Main Campus)', '121 Esselen Street, Sunnyside'),
('Metro Apartments', 'Pretoria West (Main Campus)', '54 Jeppe Street, Sunnyside'),
('Queens Residency', 'Pretoria West (Main Campus)', '205 Celliers Street, Sunnyside'),
('Mamelodi Gardens', 'Pretoria West (Main Campus)', '44 Steve Biko Street, Arcadia'),
('Millennium Heights', 'Pretoria West (Main Campus)', 'Cnr Kotze and Prinsloo Street, Sunnyside'),
('Cedar Place', 'Pretoria West (Main Campus)', '68 Belvedere Street, Arcadia'),
('Ekhaya Junction', 'Pretoria West (Main Campus)', '41 Justice Mahomed Street, Sunnyside'),
('Kopano Court', 'Pretoria West (Main Campus)', '93 Hamilton Street, Arcadia'),
('Nelson Court', 'Pretoria West (Main Campus)', '12 Park Street, Arcadia'),
('Zebra Heights', 'Pretoria West (Main Campus)', '63 Leyds Street, Sunnyside'),
('Campus Lodge', 'Pretoria West (Main Campus)', '115 Walker Street, Sunnyside'),
('Sunnyside Square', 'Pretoria West (Main Campus)', 'Corner Reitz & Leyds Street, Sunnyside'),
('Brooklyn Heights', 'Pretoria West (Main Campus)', '97 Middel Street, Brooklyn'),
('ResLink Court', 'Pretoria West (Main Campus)', '38 Minnaar Street, Arcadia'),
('Empire Student Living', 'Pretoria West (Main Campus)', '75 Leyds Street, Sunnyside'),
('The Lofts', 'Pretoria West (Main Campus)', '56 Troye Street, Sunnyside'),
('Urban Hive', 'Pretoria West (Main Campus)', '64 Beatrix Street, Arcadia'),
('Central Park Residence', 'Pretoria West (Main Campus)', '34 Francis Baard Street, Arcadia'),
('Heritage Heights', 'Pretoria West (Main Campus)', '100 Du Toit Street, Arcadia'),
('Hilltop Student Living', 'Pretoria West (Main Campus)', '21 Rissik Street, Sunnyside'),
('Metro Studios', 'Pretoria West (Main Campus)', '59 Troye Street, Sunnyside'),
('EduStay', 'Pretoria West (Main Campus)', '49 Johnston Street, Sunnyside'),
('Prime Residence', 'Pretoria West (Main Campus)', '15 Bourke Street, Sunnyside'),
('Urban Park', 'Pretoria West (Main Campus)', '18 Park Street, Arcadia'),
('Tshwane Heights', 'Pretoria West (Main Campus)', '71 Steve Biko Road, Arcadia');