update public.seo_pages set
content_blocks = case path
when '/' then jsonb_build_array(jsonb_build_object('heading','Living, AI and Opportunity in one student platform','paragraphs',jsonb_build_array('ResKonnect connects accommodation, education applications, opportunity discovery and student-housing intelligence through one public search architecture.')),jsonb_build_object('heading','Search by real need','paragraphs',jsonb_build_array('Students can find accommodation and application support, graduates can find WIL and workplace opportunities, and property owners or investors can explore student-housing intelligence.')))
when '/student-accommodation' then jsonb_build_array(jsonb_build_object('heading','Find student accommodation by campus, area and funding type','paragraphs',jsonb_build_array('ResKonnect organises student accommodation around institution, campus, suburb, budget, room type and funding compatibility.')),jsonb_build_object('heading','Current information with verification context','paragraphs',jsonb_build_array('Published residence information comes from the ResKonnect accommodation dataset and current availability or accreditation claims should be confirmed before commitment.')))
when '/student-accommodation/pretoria' then jsonb_build_array(jsonb_build_object('heading','Student accommodation across Pretoria','paragraphs',jsonb_build_array('ResKonnect connects Pretoria accommodation discovery to institutions including TUT, UP, UNISA and SMU and to the campus areas where students actually search.')),jsonb_build_object('heading','Search Pretoria by campus and suburb','paragraphs',jsonb_build_array('Priority areas include Pretoria West, Hatfield, Arcadia, Sunnyside, Soshanguve and Ga-Rankuwa, with indexable pages created only when real inventory or original local information makes them useful.')))
when '/applications' then jsonb_build_array(jsonb_build_object('heading','University, TVET and private-college application readiness','paragraphs',jsonb_build_array('ResKonnect helps applicants understand institutions, programmes, documents and application-readiness requirements before using the appropriate official application route.')),jsonb_build_object('heading','Source-aware Course Match','paragraphs',jsonb_build_array('Course Match and APS guidance are decision-support tools connected to institution records and source material, not substitutes for official admission decisions.')))
when '/opportunities' then jsonb_build_array(jsonb_build_object('heading','WIL, internships, SETA programmes and graduate opportunities','paragraphs',jsonb_build_array('ResKonnect organises workplace and career opportunities into clear opportunity types, locations, closing dates and official application routes.')),jsonb_build_object('heading','Public discovery, private applicant workflows','paragraphs',jsonb_build_array('Opportunity pages can be searchable while applicant documents and case-management records stay inside protected account areas excluded from public indexing.')))
when '/opportunities/internships' then jsonb_build_array(jsonb_build_object('heading','Current internship and graduate opportunity discovery','paragraphs',jsonb_build_array('Published opportunity pages should identify the organisation, location, date posted, closing date, requirements and official application route where available.')),jsonb_build_object('heading','Freshness is mandatory','paragraphs',jsonb_build_array('Expired opportunities are updated or archived so search users are not directed to misleading application pages.')))
when '/opportunities/seta' then jsonb_build_array(jsonb_build_object('heading','SETA-linked workplace experience and WIL','paragraphs',jsonb_build_array('ResKonnect surfaces verified SETA-linked opportunities relevant to students, TVET graduates and other eligible applicants.')),jsonb_build_object('heading','Official programme information first','paragraphs',jsonb_build_array('Requirements, deadlines and application routes should be grounded in the current official programme information whenever possible.')))
when '/properties' then jsonb_build_array(jsonb_build_object('heading','Student-housing property intelligence','paragraphs',jsonb_build_array('ResKonnect brings together student residences for sale, third-party auctions, conversion opportunities and development sites relevant to student housing.')),jsonb_build_object('heading','Analyse before you acquire','paragraphs',jsonb_build_array('Where data is available, ResKonnect can compare acquisition cost per advertised bed, location and demand indicators, accreditation claims and due-diligence notes while keeping source facts separate from ResKonnect analysis.')))
when '/property-auctions' then jsonb_build_array(jsonb_build_object('heading','Third-party property auctions relevant to student housing','paragraphs',jsonb_build_array('Unless explicitly stated otherwise, auctions displayed by ResKonnect are conducted by independent auctioneers or sheriffs and participation occurs through the official auction source.')),jsonb_build_object('heading','Auction information with verification context','paragraphs',jsonb_build_array('Auction dates, reserve or opening bids, sale-in-execution status and capacity can change, so source and last-verification information must remain visible.')))
when '/student-accommodation-for-sale' then jsonb_build_array(jsonb_build_object('heading','Student residences, houses and buildings for sale','paragraphs',jsonb_build_array('This area is for assets with an existing student-housing use or a credible student-accommodation investment case rather than every residential property near a campus.')),jsonb_build_object('heading','Separate operating assets from conversion opportunities','paragraphs',jsonb_build_array('Existing residences, ordinary houses, flats, apartment blocks and development land carry different planning, accreditation and operating risks and are classified separately.')))
when '/development-opportunities' then jsonb_build_array(jsonb_build_object('heading','Buildings and land with student-housing potential','paragraphs',jsonb_build_array('Potential student capacity is not permission to build or operate and must be tested against zoning, approved plans, fire requirements, services and occupancy rules.')),jsonb_build_object('heading','Due diligence before conversion','paragraphs',jsonb_build_array('Town-planning feasibility, approved plans, structural condition, municipal accounts and accreditation requirements should be confirmed before valuing a site on future student beds.')))
when '/ai' then jsonb_build_array(jsonb_build_object('heading','AI connected to structured ResKonnect data','paragraphs',jsonb_build_array('ResKonnect AI is designed to work with structured accommodation, institution, programme, opportunity and property records rather than relying only on generic generated answers.')),jsonb_build_object('heading','Source-aware student and property intelligence','paragraphs',jsonb_build_array('When official confirmation is required, AI output should make that limitation clear and direct the user to the authoritative source while private user data remains protected.')))
else content_blocks end,
entity_facts = case path
when '/' then jsonb_build_array(jsonb_build_object('label','Brand','value','ResKonnect'),jsonb_build_object('label','Primary pillars','value','Living • AI • Opportunity'),jsonb_build_object('label','Market','value','South Africa'))
when '/student-accommodation' then jsonb_build_array(jsonb_build_object('label','Service','value','Student accommodation discovery'),jsonb_build_object('label','Coverage model','value','Institution, campus, location and residence'),jsonb_build_object('label','Country','value','South Africa'))
when '/applications' then jsonb_build_array(jsonb_build_object('label','Services','value','Application readiness, APS guidance and Course Match'),jsonb_build_object('label','Institution types','value','Universities, TVET colleges and private colleges'))
when '/opportunities' then jsonb_build_array(jsonb_build_object('label','Opportunity types','value','WIL, internships, SETA, graduate opportunities and bursaries'),jsonb_build_object('label','Private applicant data','value','Excluded from public indexing'))
when '/properties' then jsonb_build_array(jsonb_build_object('label','Market','value','Student-housing property'),jsonb_build_object('label','Opportunity types','value','For sale, auction, conversion and development'),jsonb_build_object('label','Role','value','Discovery and property intelligence'))
when '/property-auctions' then jsonb_build_array(jsonb_build_object('label','Platform role','value','Third-party auction discovery unless expressly stated otherwise'),jsonb_build_object('label','Bidding','value','Completed with the appointed auctioneer or sheriff'))
when '/ai' then jsonb_build_array(jsonb_build_object('label','Product','value','ResKonnect AI'),jsonb_build_object('label','Data principle','value','Structured source-aware ResKonnect data'))
else entity_facts end,
cta = case path
when '/' then jsonb_build_object('label','Explore ResKonnect','to','/get-started')
when '/student-accommodation' then jsonb_build_object('label','Find student accommodation','to','/find')
when '/student-accommodation/pretoria' then jsonb_build_object('label','Browse Pretoria accommodation','to','/find')
when '/applications' then jsonb_build_object('label','Explore applications','to','/applications')
when '/opportunities' then jsonb_build_object('label','Explore opportunities','to','/opportunities')
when '/opportunities/internships' then jsonb_build_object('label','View opportunities','to','/opportunities')
when '/opportunities/seta' then jsonb_build_object('label','View opportunities','to','/opportunities')
when '/properties' then jsonb_build_object('label','Explore property intelligence','to','/properties')
when '/property-auctions' then jsonb_build_object('label','View property auctions','to','/property-auctions')
when '/student-accommodation-for-sale' then jsonb_build_object('label','Explore properties for sale','to','/student-accommodation-for-sale')
when '/development-opportunities' then jsonb_build_object('label','Explore development opportunities','to','/development-opportunities')
when '/ai' then jsonb_build_object('label','Explore ResKonnect AI','to','/ai')
else cta end,
quality_score=case when path in ('/','/student-accommodation','/applications','/opportunities','/properties') then 95 else greatest(quality_score,90) end,
content_completeness=greatest(content_completeness,90),unique_data_score=greatest(unique_data_score,55),ai_citation_ready=true,last_verified_at=now(),updated_at=now()
where path in ('/','/student-accommodation','/student-accommodation/pretoria','/applications','/opportunities','/opportunities/internships','/opportunities/seta','/properties','/property-auctions','/student-accommodation-for-sale','/development-opportunities','/ai');
