import { useCallback, useEffect, useMemo, useState } from "react";
import AdminLayout from "@/components/admin/AdminLayout";
import SEO from "@/components/SEO";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { BarChart3, Building2, Eye, Handshake, Link2, Plus, RefreshCw, Rocket, Target, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const emptyPartner={name:"",slug:"",partnership_type:"strategic",status:"active",visibility:"public",public_path:"/partners",conversion_goal:"",notes:""};
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export default function AdminPartnershipCommandCentre(){
  const [days,setDays]=useState("30");const [summary,setSummary]=useState<any>(null);const [partners,setPartners]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [draft,setDraft]=useState<any>(emptyPartner);const [editing,setEditing]=useState<string|null>(null);const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const [{data:s,error:se},{data:p,error:pe}]=await Promise.all([(supabase as any).rpc("admin_partnership_command_center",{p_days:Number(days)||30}),(supabase as any).from("partnerships").select("*").order("updated_at",{ascending:false})]);if(se)toast.error(se.message||"Could not load partnership intelligence");if(pe)toast.error(pe.message||"Could not load partners");setSummary(s||null);setPartners(p||[]);setLoading(false);},[days]);
  useEffect(()=>{void load();},[load]);
  const totals=summary?.totals||{};
  const edit=(p:any)=>{setEditing(p.id);setDraft({...emptyPartner,...p});setOpen(true);};
  const create=()=>{setEditing(null);setDraft(emptyPartner);setOpen(true);};
  const save=async()=>{if(!draft.name.trim())return toast.error("Partner name is required");setSaving(true);const payload={name:draft.name.trim(),slug:slugify(draft.slug||draft.name),partnership_type:draft.partnership_type,status:draft.status,visibility:draft.visibility,public_path:draft.public_path||null,conversion_goal:draft.conversion_goal||null,notes:draft.notes||null,updated_at:new Date().toISOString()};const result=editing?await (supabase as any).from("partnerships").update(payload).eq("id",editing):await (supabase as any).from("partnerships").insert(payload);setSaving(false);if(result.error)return toast.error(result.error.message||"Could not save partnership");toast.success(editing?"Partnership updated":"Partnership created");setOpen(false);await load();};
  const partnerRows=summary?.partners||[];const recruitment=summary?.recruitment||[];
  const funnelTotal=Number(totals.partnerApplications||0)+Number(totals.partnerReservations||0)+Number(totals.partnerPlacements||0);
  const visibilityPct=Number(totals.activePartners||0)>0?Math.round(Number(totals.publicPartners||0)/Number(totals.activePartners)*100):0;

  return <AdminLayout><SEO noIndex title="Partnership Command Centre | ResKonnect Admin" description="God-mode partnership visibility, attribution and conversion intelligence."/><div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-primary">Growth · Partnership OS</p><h1 className="mt-1 text-3xl font-black">Partnership Command Centre</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">One control plane for strategic partners, creator channels, residence recruitment, public visibility, attribution and conversion outcomes.</p></div><div className="flex flex-wrap gap-2"><Select value={days} onValueChange={setDays}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="7">Last 7 days</SelectItem><SelectItem value="30">Last 30 days</SelectItem><SelectItem value="90">Last 90 days</SelectItem></SelectContent></Select><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</Button><Button onClick={create}><Plus className="mr-2 h-4 w-4"/>New partner</Button></div></div>

    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-6"><Metric icon={Handshake} label="Active partners" value={totals.activePartners||0}/><Metric icon={Eye} label="Public visibility" value={`${visibilityPct}%`}/><Metric icon={Users} label="Attributed users" value={totals.attributedUsers||0}/><Metric icon={BarChart3} label="Partner page views" value={totals.partnerPageViews||0}/><Metric icon={Rocket} label="Partner conversions" value={funnelTotal}/><Metric icon={Link2} label="Recruiter-res links" value={totals.activeRecruiterResidenceLinks||0}/></div>

    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
      <Card><CardHeader><CardTitle>Partner performance</CardTitle></CardHeader><CardContent>{partnerRows.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No partnership performance yet.</p>:<div className="space-y-3">{partnerRows.map((p:any)=><button key={p.id} type="button" onClick={()=>{const full=partners.find((x)=>x.id===p.id);if(full)edit(full);}} className="grid w-full gap-3 rounded-2xl border p-4 text-left transition hover:border-primary/30 md:grid-cols-[1fr_repeat(4,90px)] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-black">{p.name}</p><Badge variant={p.status==="active"?"default":"secondary"}>{p.status}</Badge><Badge variant="outline">{p.visibility}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{p.partnership_type} · {p.public_path||"Internal"}</p></div><Stat label="Views" value={p.views}/><Stat label="Applications" value={p.applications}/><Stat label="Reservations" value={p.reservations}/><Stat label="Placements" value={p.placements}/></button>)}</div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Network power</CardTitle></CardHeader><CardContent className="space-y-3"><Network label="Creator partners" value={totals.creatorPartners||0}/><Network label="Approved recruiters" value={totals.activeRecruiters||0}/><Network label="Recruitable residences" value={totals.recruitableResidences||0}/><Network label="Active residence links" value={totals.activeRecruiterResidenceLinks||0}/><div className="rounded-2xl border border-primary/20 bg-primary/5 p-4"><p className="text-sm font-bold">God-mode rule</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Public visibility, partner status and commercial configuration are centrally controlled. Residence portals receive only their own aggregate recruitment performance and no student contact data.</p></div></CardContent></Card>
    </div>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="h-5 w-5 text-primary"/>Residence recruitment conversion channels</CardTitle></CardHeader><CardContent>{recruitment.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No residences have opted into the recruiter network yet.</p>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{recruitment.map((r:any)=><div key={r.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-black">{r.name}</p><p className="text-xs text-muted-foreground">Listing quality {r.data_quality_score||0}%</p></div><Badge>Recruiting</Badge></div><div className="mt-4 grid grid-cols-4 gap-2"><Stat label="Recruiters" value={r.recruiters}/><Stat label="Clicks" value={r.clicks}/><Stat label="Apps" value={r.applications}/><Stat label="Placed" value={r.placements}/></div></div>)}</div>}</CardContent></Card>

    <Card><CardHeader><CardTitle>Partnership registry</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{partners.map((p)=><button key={p.id} onClick={()=>edit(p)} className="rounded-2xl border p-4 text-left hover:border-primary/30"><div className="flex items-center justify-between gap-2"><p className="font-black">{p.name}</p><Badge variant={p.status==="active"?"default":"secondary"}>{p.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{p.partnership_type}</p><div className="mt-3 flex items-center gap-2"><Badge variant="outline">{p.visibility}</Badge>{p.public_path&&<span className="truncate text-xs text-muted-foreground">{p.public_path}</span>}</div></button>)}</CardContent></Card>

    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{editing?"Edit partnership":"Create partnership"}</DialogTitle><DialogDescription>Control visibility, lifecycle and conversion intent. Attribution can use links with ?partner=partner-slug.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Partner name"><Input value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value,slug:editing?draft.slug:slugify(e.target.value)})}/></Field><Field label="Slug"><Input value={draft.slug} onChange={(e)=>setDraft({...draft,slug:slugify(e.target.value)})}/></Field><Field label="Partnership type"><Input value={draft.partnership_type} onChange={(e)=>setDraft({...draft,partnership_type:e.target.value})}/></Field><Field label="Public path"><Input value={draft.public_path||""} onChange={(e)=>setDraft({...draft,public_path:e.target.value})}/></Field><Field label="Status"><Select value={draft.status} onValueChange={(v)=>setDraft({...draft,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="prospect">Prospect</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="paused">Paused</SelectItem><SelectItem value="ended">Ended</SelectItem></SelectContent></Select></Field><Field label="Visibility"><Select value={draft.visibility} onValueChange={(v)=>setDraft({...draft,visibility:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="public">Public</SelectItem><SelectItem value="private">Private</SelectItem><SelectItem value="internal">Internal</SelectItem></SelectContent></Select></Field><div className="sm:col-span-2"><Field label="Conversion goal"><Input value={draft.conversion_goal||""} onChange={(e)=>setDraft({...draft,conversion_goal:e.target.value})}/></Field></div><div className="sm:col-span-2"><Field label="Internal notes"><Textarea rows={4} value={draft.notes||""} onChange={(e)=>setDraft({...draft,notes:e.target.value})}/></Field></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={()=>void save()} disabled={saving}>{saving?"Saving…":"Save partnership"}</Button></DialogFooter></DialogContent></Dialog>
  </div></AdminLayout>;
}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <Card><CardContent className="p-4"><Icon className="h-4 w-4 text-primary"/><p className="mt-2 text-2xl font-black">{value}</p><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p></CardContent></Card>;}
function Stat({label,value}:{label:string;value:any}){return <div className="text-center md:text-left"><p className="text-lg font-black">{Number(value||0).toLocaleString("en-ZA")}</p><p className="text-[9px] font-bold uppercase tracking-wide text-muted-foreground">{label}</p></div>;}
function Network({label,value}:{label:string;value:any}){return <div className="flex items-center justify-between rounded-xl bg-muted/35 p-3"><span className="text-sm text-muted-foreground">{label}</span><strong>{Number(value||0).toLocaleString("en-ZA")}</strong></div>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>;}
