import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import SEO from '@/components/SEO';
import AdminLayout from '@/components/admin/AdminLayout';
import ContactExportButtons from '@/components/admin/ContactExportButtons';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Field, Panel, selectStyle } from '@/components/student-care/CareUI';
import { db, friendlyStatus, readAllPages } from '@/lib/studentCare';
import { downloadText, toCsv } from '@/lib/contactExport';
import { toast } from 'sonner';
const feedbackStates = ['received','reviewing','raised_with_residence','raised_with_institution','resolved'];
const roomStates = ['waiting','searching','matched','placed','withdrawn'];
const stayPeriod = (value:unknown) => Number(value) === 3 ? 'Both semesters / full academic year' : Number(value) === 2 ? 'Second semester' : 'First semester';
export default function AdminStudentCare() {
  const [tab,setTab] = useState('feedback'),[error,setError] = useState(''),[loading,setLoading] = useState(true),[busy,setBusy] = useState(false),[search,setSearch] = useState(''),[campaign,setCampaign] = useState('all');
  const [campaigns,setCampaigns] = useState<any[]>([]),[feedback,setFeedback] = useState<any[]>([]),[rooms,setRooms] = useState<any[]>([]),[partners,setPartners] = useState<any[]>([]),[calls,setCalls] = useState<any[]>([]),[profiles,setProfiles] = useState<any[]>([]),[placements,setPlacements] = useState<any[]>([]);
  const [newCampaign,setNewCampaign] = useState({title:'',academic_year:'2027',description:''});
  const load = async () => {
    setLoading(true);
    try {
      const r = await Promise.all(['residence_feedback_campaigns','residence_stay_feedback','single_room_waitlist','creator_partners','assistance_call_requests','profiles','student_care_placements'].map(t => readAllPages(() => db.from(t).select(t === 'profiles' ? 'id,full_name,email' : '*').order(t === 'student_care_placements' ? 'user_id' : 'id'))));
      setCampaigns(r[0]);setFeedback(r[1]);setRooms(r[2]);setPartners(r[3]);setCalls(r[4]);setProfiles(r[5]);setPlacements(r[6]);setError('');
    } catch(e:any) {setError(e.message || 'Could not load care records');} finally {setLoading(false);}
  };
  useEffect(() => {void load();},[]);
  const patch = async(table:string,id:string,p:any) => {
    setBusy(true);
    try {const r = await db.from(table).update(p).eq(table === 'student_care_placements' ? 'user_id' : 'id',id).select('*').single();if(r.error) throw r.error;toast.success('Saved');await load();return true;}
    catch(e:any) {toast.error(e.message || 'Could not save');return false;} finally {setBusy(false);}
  };
  const visible = feedback.filter(r => (campaign === 'all' || r.campaign_id === campaign) && [r.residence_name,r.campus,r.institution,r.status].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b) => Number(b.urgent_safety_concern)-Number(a.urgent_safety_concern) || b.created_at.localeCompare(a.created_at));
  const exportFeedback = (petition:boolean) => {
    const rows = visible.filter(r => r.share_with_institution && (!petition || r.petition_support));if(!rows.length) return toast.info('No consented responses match these filters');
    if(petition) {
      const body = ['RESKONNECT — STUDENT RESIDENCE PETITION','Students first. Quality throughout the year.','','We request that the responsible residences and institutions review these concerns, respond to ResKonnect and provide a clear action plan.','Consenting supporters: '+rows.length,'',...rows.flatMap((r,i) => [(i+1)+'. '+r.residence_name+' · '+r.institution+' · '+r.campus+' · '+stayPeriod(r.stay_semester),'Requested improvements: '+r.improvements,'Feedback: '+r.concerns,'Supporter: '+(r.share_identity ? profiles.find(p => p.id === r.user_id)?.full_name || 'Name unavailable' : 'Identity withheld by student'),'']),'Institution response / action plan: __________________________________','Responsible person: ____________________  Review date: ______________'].join('\n');
      downloadText('ResKonnect_Residence_Petition.txt',body,'text/plain;charset=utf-8');
    } else downloadText('ResKonnect_Consented_Residence_Feedback.csv',toCsv(rows.map(r => ({Residence:r.residence_name,Institution:r.institution,Campus:r.campus,'Period reviewed':stayPeriod(r.stay_semester),Name:r.share_identity ? profiles.find(p => p.id === r.user_id)?.full_name || '' : 'Identity withheld',Safety:r.safety_rating,Maintenance:r.maintenance_rating,Management:r.management_rating,Overall:r.overall_rating,Feedback:r.concerns,Improvements:r.improvements,Petition:r.petition_support ? 'Yes' : 'No',Status:r.status,'ResKonnect response':r.staff_response,'Institution response':r.institution_response}))),'text/csv;charset=utf-8');
  };
  return <AdminLayout><SEO noIndex title="Student Care & Application Partners | ResKonnect Admin" description="Manage residence feedback, single-room requests, application partners and student support." />
    <main className="space-y-6 p-4 sm:p-6"><header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-black">Student Care & Applications</h1><p className="mt-2 text-sm text-muted-foreground">Track the concern, the response and the outcome. Students can stay for both semesters under their accommodation agreement.</p></div><Button variant="outline" onClick={() => void load()}>Refresh</Button></header>
      <Panel title="All WhatsApp and platform contacts"><p className="text-sm text-muted-foreground">Importable contacts named RK 2027, with campus, preferred residence and useful application details.</p><ContactExportButtons /></Panel>
      <nav className="flex flex-wrap gap-2" aria-label="Care administration">{[['feedback','Residence feedback',feedback.length],['rooms','Single rooms',rooms.filter(r => r.status !== 'withdrawn').length],['partners','Application partners',partners.length],['calls','Call requests',calls.filter(c => ['requested','scheduled'].includes(c.status)).length],['placements','Placed students',placements.filter(p => p.care_status === 'placed').length]].map(([value,label,count]) => <Button key={String(value)} variant={tab === value ? 'default' : 'outline'} onClick={() => setTab(String(value))}>{label} ({count})</Button>)}</nav>
      {error && <p role="alert" className="rounded-xl border border-destructive p-4">{error}</p>}{loading && <p className="text-sm text-muted-foreground">Loading records…</p>}
      {tab === 'feedback' && <><Panel title="Reusable feedback campaigns"><form className="grid gap-3 md:grid-cols-[1fr_120px_1fr_auto]" onSubmit={async e => {e.preventDefault();setBusy(true);const r = await db.from('residence_feedback_campaigns').insert({...newCampaign,academic_year:Number(newCampaign.academic_year)});setBusy(false);if(r.error) return toast.error(r.error.message);setNewCampaign({...newCampaign,title:'',description:''});toast.success('Reusable feedback campaign created');await load();}}><Input required minLength={3} maxLength={160} aria-label="Campaign title" placeholder="Year-end residence feedback" value={newCampaign.title} onChange={e => setNewCampaign({...newCampaign,title:e.target.value})}/><Input required type="number" min="2020" max="2100" aria-label="Campaign year" value={newCampaign.academic_year} onChange={e => setNewCampaign({...newCampaign,academic_year:e.target.value})}/><Input aria-label="Campaign instructions" placeholder="Purpose / instructions" value={newCampaign.description} onChange={e => setNewCampaign({...newCampaign,description:e.target.value})}/><Button disabled={busy}>Create reusable form</Button></form>
        <div className="divide-y">{campaigns.map(c => <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-bold">{c.title}</p><p className="text-xs text-muted-foreground">{c.academic_year} · {c.is_active ? 'Open' : 'Closed'}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={async () => {try {await navigator.clipboard.writeText(window.location.origin+'/student-care?campaign='+c.id);toast.success('Reusable form link copied');}catch{toast.error('Could not copy');}}}>Copy form link</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void patch('residence_feedback_campaigns',c.id,{is_active:!c.is_active})}>{c.is_active ? 'Close' : 'Reopen'}</Button></div></div>)}</div>
      </Panel><div className="flex flex-wrap gap-3"><select className="rounded-md border bg-background p-2" aria-label="Feedback campaign" value={campaign} onChange={e => setCampaign(e.target.value)}><option value="all">All campaigns</option>{campaigns.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select><Input className="sm:max-w-xs" aria-label="Filter feedback" placeholder="Residence, campus, institution…" value={search} onChange={e => setSearch(e.target.value)}/><Button variant="outline" onClick={() => exportFeedback(false)}>Export consented feedback</Button><Button variant="outline" onClick={() => exportFeedback(true)}>Download petition</Button></div><p className="text-xs text-muted-foreground">Exports include only students who agreed to sharing. Review free-text comments before forwarding. Exporting does not send a report.</p>{!visible.length && <p className="rounded-xl border border-dashed p-8 text-center text-sm">No feedback matches these filters.</p>}{visible.map(r => <CareRecord key={r.id} row={r} kind="feedback" busy={busy} save={p => patch('residence_stay_feedback',r.id,p)} />)}</>}
      {tab === 'rooms' && <><p className="rounded-xl bg-muted/40 p-4 text-sm">Every entry is strictly for a single room. Full-year requests cover both semesters; first- and second-semester requests indicate when students need accommodation, not their contractual move-out date. Verify single-room availability and offer terms when matching.</p>{!rooms.length && <p>No single-room requests yet.</p>}{rooms.map(r => <CareRecord key={r.id} row={r} kind="room" busy={busy} save={p => patch('single_room_waitlist',r.id,p)} />)}</>}
      {tab === 'partners' && <Panel title="Partner approval & fee controls"><p className="text-sm text-muted-foreground">Invite partners to <Link to="/application-partners" className="underline">apply here</Link>. Approve only partners you have checked. The R100 cap is enforced in the backend.</p>{partners.map(p => <div key={p.id} className="flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><h2 className="font-bold">{p.display_name} <Badge variant="outline">{p.partner_kind}</Badge></h2><p className="mt-1 text-sm text-muted-foreground">{p.bio}</p><p className="mt-2 font-semibold">R{Number(p.assistance_fee).toFixed(2)} per annual case</p></div><select className="rounded-md border bg-background p-2" aria-label={'Approval for '+p.display_name} disabled={busy} value={p.status} onChange={e => void patch('creator_partners',p.id,{status:e.target.value})}>{['pending','active','paused','rejected'].map(s => <option key={s}>{s}</option>)}</select></div>)}</Panel>}
      {tab === 'calls' && <div className="grid gap-4 md:grid-cols-2">{calls.map(c => <Panel title={c.topic} key={c.id}><Badge>{c.status}</Badge><p className="text-sm">{c.phone} · {new Date(c.preferred_at).toLocaleString('en-ZA')}</p><p className="text-sm">{c.staff_notes}</p><Button asChild><Link to={'/application-assistance/case/'+c.case_id}>Open case & schedule call</Link></Button></Panel>)}{!calls.length && <p>No call requests yet.</p>}</div>}
      {tab === 'placements' && <Panel title="Placement for outreach"><p className="text-sm text-muted-foreground">Applicants before 1 July 2026 are considered placed for follow-ups. Recorded residence decisions remain available. This outreach category does not mean a student may only stay for one semester. If a student requests a new search, update their care status here.</p>{placements.map(p => <div key={p.user_id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><p className="font-bold">{profiles.find(u => u.id === p.user_id)?.full_name || 'Student'}</p><p className="text-xs text-muted-foreground">{p.basis}</p></div><select className="rounded-md border bg-background p-2" aria-label="Placement for follow-ups" disabled={busy} value={p.care_status} onChange={e => void patch('student_care_placements',p.user_id,{care_status:e.target.value,updated_at:new Date().toISOString()})}><option value="placed">Placed</option><option value="seeking">Seeking accommodation again</option></select></div>)}</Panel>}
    </main></AdminLayout>;
}
function CareRecord({row,kind,busy,save}:{row:any;kind:'feedback'|'room';busy:boolean;save:(p:any)=>Promise<boolean>}) {
  const [status,setStatus] = useState(row.status),[response,setResponse] = useState(row.staff_response || ''),[institutionResponse,setInstitutionResponse] = useState(row.institution_response || ''),[single,setSingle] = useState(false);
  return <Panel title={kind === 'room' ? row.full_name : row.residence_name}><div className="flex gap-2">{row.urgent_safety_concern && <Badge variant="destructive">Safety concern</Badge>}<Badge variant="secondary">{friendlyStatus(row.status)}</Badge></div><p className="text-sm text-muted-foreground">{row.campus} · {kind === 'room' ? row.academic_year+' · '+stayPeriod(row.semester)+' · '+row.phone : row.institution+' · '+stayPeriod(row.stay_semester)}</p>
    {kind === 'room' ? <p className="text-sm">Preferred: {row.preferred_residence || 'Flexible'} · Budget: {row.budget == null ? 'Not specified' : 'R'+row.budget} · Funding: {row.funding_type}<br/>{row.notes}</p> : <><p className="text-sm">Safety {row.safety_rating}/5 · Maintenance {row.maintenance_rating}/5 · Management {row.management_rating}/5 · Overall {row.overall_rating}/5</p><p className="whitespace-pre-wrap text-sm">{row.concerns}</p><p className="whitespace-pre-wrap text-sm"><strong>Requested improvements: </strong>{row.improvements}</p><p className="text-xs text-muted-foreground">Sharing: {row.share_with_institution ? 'Consented' : 'Internal only'} · Petition: {row.petition_support ? 'Supports' : 'Not selected'}</p></>}
    <form className="grid gap-3 sm:grid-cols-2" onSubmit={e => {e.preventDefault();if(kind === 'room' && ['matched','placed'].includes(status) && !single) return toast.error('Confirm that this is a single room');void save({status,staff_response:response,updated_at:new Date().toISOString(),...(kind === 'feedback' ? {institution_response:institutionResponse} : {})});}}>
      <Field label="Care status"><select className={selectStyle} value={status} onChange={e => setStatus(e.target.value)}>{(kind === 'room' ? roomStates : feedbackStates).map(s => <option key={s} value={s}>{friendlyStatus(s)}</option>)}</select></Field><Field label="Update visible to the student"><Textarea required maxLength={5000} value={response} onChange={e => setResponse(e.target.value)} placeholder={kind === 'room' ? 'Single-room option and next step' : 'Action taken, responsible team and next review date'}/></Field>
      {kind === 'feedback' && <Field label="Residence / institution response & action plan" wide><Textarea value={institutionResponse} onChange={e => setInstitutionResponse(e.target.value)}/></Field>}
      {kind === 'room' && ['matched','placed'].includes(status) && <label className="flex gap-2 text-sm sm:col-span-2"><input required type="checkbox" checked={single} onChange={e => setSingle(e.target.checked)}/>I verified that this option is a single room.</label>}
      <Button disabled={busy} className="sm:col-span-2">Save care update</Button>
    </form></Panel>;
}
